-- 1. Tablas Base
ALTER TABLE FIDE_ESTADOS_TB ADD (CREADO_POR VARCHAR2(100), FECHA_CREACION TIMESTAMP, MODIFICADO_POR VARCHAR2(100), FECHA_MODIFICACION TIMESTAMP, ACCION VARCHAR2(100));
ALTER TABLE FIDE_ROLES_TB ADD (CREADO_POR VARCHAR2(100), FECHA_CREACION TIMESTAMP, MODIFICADO_POR VARCHAR2(100), FECHA_MODIFICACION TIMESTAMP, ACCION VARCHAR2(100));
ALTER TABLE FIDE_PROVINCIA_TB ADD (CREADO_POR VARCHAR2(100), FECHA_CREACION TIMESTAMP, MODIFICADO_POR VARCHAR2(100), FECHA_MODIFICACION TIMESTAMP, ACCION VARCHAR2(100));
ALTER TABLE FIDE_METODO_PAGO_TB ADD (CREADO_POR VARCHAR2(100), FECHA_CREACION TIMESTAMP, MODIFICADO_POR VARCHAR2(100), FECHA_MODIFICACION TIMESTAMP, ACCION VARCHAR2(100));
ALTER TABLE FIDE_CATEGORIA_PRODUCTO_TB ADD (CREADO_POR VARCHAR2(100), FECHA_CREACION TIMESTAMP, MODIFICADO_POR VARCHAR2(100), FECHA_MODIFICACION TIMESTAMP, ACCION VARCHAR2(100));
ALTER TABLE FIDE_CATEGORIA_SERVICIO_TB ADD (CREADO_POR VARCHAR2(100), FECHA_CREACION TIMESTAMP, MODIFICADO_POR VARCHAR2(100), FECHA_MODIFICACION TIMESTAMP, ACCION VARCHAR2(100));
ALTER TABLE FIDE_PAQUETE_TB ADD (CREADO_POR VARCHAR2(100), FECHA_CREACION TIMESTAMP, MODIFICADO_POR VARCHAR2(100), FECHA_MODIFICACION TIMESTAMP, ACCION VARCHAR2(100));

-- 2. Tablas Geográficas y Usuarios
ALTER TABLE FIDE_CANTON_TB ADD (CREADO_POR VARCHAR2(100), FECHA_CREACION TIMESTAMP, MODIFICADO_POR VARCHAR2(100), FECHA_MODIFICACION TIMESTAMP, ACCION VARCHAR2(100));
ALTER TABLE FIDE_DISTRITO_TB ADD (CREADO_POR VARCHAR2(100), FECHA_CREACION TIMESTAMP, MODIFICADO_POR VARCHAR2(100), FECHA_MODIFICACION TIMESTAMP, ACCION VARCHAR2(100));
ALTER TABLE FIDE_USUARIOS_TB ADD (CREADO_POR VARCHAR2(100), FECHA_CREACION TIMESTAMP, MODIFICADO_POR VARCHAR2(100), FECHA_MODIFICACION TIMESTAMP, ACCION VARCHAR2(100));

-- 3. Tablas Transaccionales Principales
ALTER TABLE FIDE_PRODUCTOS_TB ADD (CREADO_POR VARCHAR2(100), FECHA_CREACION TIMESTAMP, MODIFICADO_POR VARCHAR2(100), FECHA_MODIFICACION TIMESTAMP, ACCION VARCHAR2(100));
ALTER TABLE FIDE_SERVICIOS_TB ADD (CREADO_POR VARCHAR2(100), FECHA_CREACION TIMESTAMP, MODIFICADO_POR VARCHAR2(100), FECHA_MODIFICACION TIMESTAMP, ACCION VARCHAR2(100));
ALTER TABLE FIDE_PAGOS_TB ADD (CREADO_POR VARCHAR2(100), FECHA_CREACION TIMESTAMP, MODIFICADO_POR VARCHAR2(100), FECHA_MODIFICACION TIMESTAMP, ACCION VARCHAR2(100));

-- 4. Tablas de Personas (Hijas)
ALTER TABLE FIDE_CLIENTES_TB ADD (CREADO_POR VARCHAR2(100), FECHA_CREACION TIMESTAMP, MODIFICADO_POR VARCHAR2(100), FECHA_MODIFICACION TIMESTAMP, ACCION VARCHAR2(100));
ALTER TABLE FIDE_EMPLEADOS_TB ADD (CREADO_POR VARCHAR2(100), FECHA_CREACION TIMESTAMP, MODIFICADO_POR VARCHAR2(100), FECHA_MODIFICACION TIMESTAMP, ACCION VARCHAR2(100));
ALTER TABLE FIDE_CORREO_TB ADD (CREADO_POR VARCHAR2(100), FECHA_CREACION TIMESTAMP, MODIFICADO_POR VARCHAR2(100), FECHA_MODIFICACION TIMESTAMP, ACCION VARCHAR2(100));
ALTER TABLE FIDE_DIRECCIONES_TB ADD (CREADO_POR VARCHAR2(100), FECHA_CREACION TIMESTAMP, MODIFICADO_POR VARCHAR2(100), FECHA_MODIFICACION TIMESTAMP, ACCION VARCHAR2(100));
ALTER TABLE FIDE_RESERVACIONES_TB ADD (CREADO_POR VARCHAR2(100), FECHA_CREACION TIMESTAMP, MODIFICADO_POR VARCHAR2(100), FECHA_MODIFICACION TIMESTAMP, ACCION VARCHAR2(100));

-- 5. Tablas Intermedias y Detalles
ALTER TABLE FIDE_PAQUETES_POR_SERVICIO_TB ADD (CREADO_POR VARCHAR2(100), FECHA_CREACION TIMESTAMP, MODIFICADO_POR VARCHAR2(100), FECHA_MODIFICACION TIMESTAMP, ACCION VARCHAR2(100));
ALTER TABLE FIDE_ASIGNACION_TB ADD (CREADO_POR VARCHAR2(100), FECHA_CREACION TIMESTAMP, MODIFICADO_POR VARCHAR2(100), FECHA_MODIFICACION TIMESTAMP, ACCION VARCHAR2(100));
ALTER TABLE FIDE_DETALLE_RESERVACION_TB ADD (CREADO_POR VARCHAR2(100), FECHA_CREACION TIMESTAMP, MODIFICADO_POR VARCHAR2(100), FECHA_MODIFICACION TIMESTAMP, ACCION VARCHAR2(100));
ALTER TABLE FIDE_FACTURACION_TB ADD (CREADO_POR VARCHAR2(100), FECHA_CREACION TIMESTAMP, MODIFICADO_POR VARCHAR2(100), FECHA_MODIFICACION TIMESTAMP, ACCION VARCHAR2(100));
ALTER TABLE FIDE_DETALLE_FACTURA_TB ADD (CREADO_POR VARCHAR2(100), FECHA_CREACION TIMESTAMP, MODIFICADO_POR VARCHAR2(100), FECHA_MODIFICACION TIMESTAMP, ACCION VARCHAR2(100));

