-- Creacion del usuario para el proyecto
CREATE USER G2_SC508_VT_PROYECTO 
IDENTIFIED BY "1234";

-- ASIGNACIÓN DE PERMISOS
GRANT CREATE SESSION TO G2_SC508_VT_PROYECTO;
GRANT RESOURCE TO G2_SC508_VT_PROYECTO;
GRANT DBA TO G2_SC508_VT_PROYECTO;
GRANT CREATE VIEW TO G2_SC508_VT_PROYECTO;
GRANT CREATE MATERIALIZED VIEW TO G2_SC508_VT_PROYECTO;
COMMIT;


-- Creacion de las tablas correspondientes

--------------------------------------------------------------------------
-- 1. TABLAS BASE (SIN DEPENDENCIAS)
--------------------------------------------------------------------------

CREATE TABLE FIDE_ESTADOS_TB (
    ESTADOS_ID_ESTADO_PK NUMBER CONSTRAINT ESTADOS_ID_ESTADO_PK PRIMARY KEY,
    ambito VARCHAR2(50),
    estado VARCHAR2(50)
);

CREATE TABLE FIDE_ROLES_TB (
    ROLES_ID_ROL_PK NUMBER CONSTRAINT ROLES_ID_ROL_PK PRIMARY KEY,
    nombre_rol VARCHAR2(50),
    descripcion VARCHAR2(255)
);

CREATE TABLE FIDE_PROVINCIA_TB (
    PROVINCIA_ID_PROVINCIA_PK NUMBER CONSTRAINT PROVINCIA_ID_PROVINCIA_PK PRIMARY KEY,
    nombre VARCHAR2(100),
    -- [MODIFICACIÓN 1] Se agrega la columna de estado para borrado lógico
    ESTADOS_ID_ESTADO_FK NUMBER DEFAULT 1,
    CONSTRAINT PROVINCIA_ESTADOS_FK FOREIGN KEY (ESTADOS_ID_ESTADO_FK) 
        REFERENCES FIDE_ESTADOS_TB(ESTADOS_ID_ESTADO_PK)
);

CREATE TABLE FIDE_METODO_PAGO_TB (
    METODO_PAGO_ID_METODO_PK NUMBER CONSTRAINT METODO_PAGO_ID_METODO_PK PRIMARY KEY,
    nombre VARCHAR2(50),
    -- [MODIFICACIÓN 2] Se agrega la columna de estado para borrado lógico
    ESTADOS_ID_ESTADO_FK NUMBER DEFAULT 1,
    CONSTRAINT METODO_PAGO_ESTADOS_FK FOREIGN KEY (ESTADOS_ID_ESTADO_FK) 
        REFERENCES FIDE_ESTADOS_TB(ESTADOS_ID_ESTADO_PK)
);

CREATE TABLE FIDE_CATEGORIA_PRODUCTO_TB (
    CATEGORIA_PRODUCTO_ID_CATEGORIA_PK NUMBER CONSTRAINT CATEGORIA_PRODUCTO_ID_CATEGORIA_PK PRIMARY KEY,
    nombre VARCHAR2(100),
    descripcion VARCHAR2(255),
    -- [MODIFICACIÓN 3] Se agrega la columna de estado para borrado lógico
    ESTADOS_ID_ESTADO_FK NUMBER DEFAULT 1,
    CONSTRAINT CAT_PROD_ESTADOS_FK FOREIGN KEY (ESTADOS_ID_ESTADO_FK) 
        REFERENCES FIDE_ESTADOS_TB(ESTADOS_ID_ESTADO_PK)
);

CREATE TABLE FIDE_CATEGORIA_SERVICIO_TB (
    CATEGORIA_SERVICIO_ID_CATEGORIA_PK NUMBER CONSTRAINT CATEGORIA_SERVICIO_ID_CATEGORIA_PK PRIMARY KEY,
    nombre VARCHAR2(100),
    descripcion VARCHAR2(255),
    -- [MODIFICACIÓN 4] Se agrega la columna de estado para borrado lógico
    ESTADOS_ID_ESTADO_FK NUMBER DEFAULT 1,
    CONSTRAINT CAT_SERV_ESTADOS_FK FOREIGN KEY (ESTADOS_ID_ESTADO_FK) 
        REFERENCES FIDE_ESTADOS_TB(ESTADOS_ID_ESTADO_PK)
);

CREATE TABLE FIDE_PAQUETE_TB (
    PAQUETE_ID_PAQUETE_PK NUMBER CONSTRAINT PAQUETE_ID_PAQUETE_PK PRIMARY KEY,
    nombre_paquete VARCHAR2(100),
    descripcion VARCHAR2(255),
    precio_total NUMBER(12,2),
    -- [MODIFICACIÓN 5] Se agrega la columna de estado para borrado lógico
    ESTADOS_ID_ESTADO_FK NUMBER DEFAULT 1,
    CONSTRAINT PAQUETE_ESTADOS_FK FOREIGN KEY (ESTADOS_ID_ESTADO_FK) 
        REFERENCES FIDE_ESTADOS_TB(ESTADOS_ID_ESTADO_PK)
);


--------------------------------------------------------------------------
-- 2. TABLAS INTERMEDIAS (GEOGRAFÍA, USUARIOS BASE, PROD/SERV)
--------------------------------------------------------------------------

CREATE TABLE FIDE_CANTON_TB (
    CANTON_ID_CANTON_PK NUMBER CONSTRAINT CANTON_ID_CANTON_PK PRIMARY KEY,
    PROVINCIA_ID_PROVINCIA_PK NUMBER,
    nombre VARCHAR2(100),
    -- [MODIFICACIÓN 6] Se agrega la columna de estado para borrado lógico
    ESTADOS_ID_ESTADO_FK NUMBER DEFAULT 1,
    CONSTRAINT PROVINCIA_ID_PROVINCIA_PK_FK FOREIGN KEY (PROVINCIA_ID_PROVINCIA_PK)
        REFERENCES FIDE_PROVINCIA_TB(PROVINCIA_ID_PROVINCIA_PK),
    CONSTRAINT CANTON_ESTADOS_FK FOREIGN KEY (ESTADOS_ID_ESTADO_FK)
        REFERENCES FIDE_ESTADOS_TB(ESTADOS_ID_ESTADO_PK)
);

CREATE TABLE FIDE_DISTRITO_TB (
    DISTRITO_ID_DISTRITO_PK NUMBER CONSTRAINT DISTRITO_ID_DISTRITO_PK PRIMARY KEY,
    CANTON_ID_CANTON_PK NUMBER,
    nombre VARCHAR2(100),
    -- [MODIFICACIÓN 7] Se agrega la columna de estado para borrado lógico
    ESTADOS_ID_ESTADO_FK NUMBER DEFAULT 1,
    CONSTRAINT CANTON_ID_CANTON_PK_FK FOREIGN KEY (CANTON_ID_CANTON_PK)
        REFERENCES FIDE_CANTON_TB(CANTON_ID_CANTON_PK),
    CONSTRAINT DISTRITO_ESTADOS_FK FOREIGN KEY (ESTADOS_ID_ESTADO_FK)
        REFERENCES FIDE_ESTADOS_TB(ESTADOS_ID_ESTADO_PK)
);

CREATE TABLE FIDE_USUARIOS_TB (
    USUARIOS_ID_CEDULA_PK VARCHAR2(20) CONSTRAINT USUARIOS_ID_CEDULA_PK PRIMARY KEY,
    nombre VARCHAR2(100),
    primer_apellido VARCHAR2(100),
    segundo_apellido VARCHAR2(100),
    contrasena VARCHAR2(255),
    ESTADOS_ID_ESTADO_PK NUMBER,
    ROLES_ID_ROL_PK NUMBER,
    CONSTRAINT ESTADOS_ID_ESTADO_PK_FK FOREIGN KEY (ESTADOS_ID_ESTADO_PK)
        REFERENCES FIDE_ESTADOS_TB(ESTADOS_ID_ESTADO_PK),
    CONSTRAINT ROLES_ID_ROL_PK_FK FOREIGN KEY (ROLES_ID_ROL_PK)
        REFERENCES FIDE_ROLES_TB(ROLES_ID_ROL_PK)
);

CREATE TABLE FIDE_PRODUCTOS_TB (
    PRODUCTO_ID_PRODUCTO_PK NUMBER CONSTRAINT PRODUCTO_ID_PRODUCTO_PK PRIMARY KEY,
    nombre VARCHAR2(100),
    descripcion VARCHAR2(255),
    precio_unitario NUMBER(12,2),
    cantidad NUMBER,
    CATEGORIA_PRODUCTO_ID_CATEGORIA_PK NUMBER,
    ESTADOS_ID_ESTADO_PK NUMBER,
    CONSTRAINT PRODUCTO_CATEGORIA_ID_CATEGORIA_PK_FK FOREIGN KEY (CATEGORIA_PRODUCTO_ID_CATEGORIA_PK)
        REFERENCES FIDE_CATEGORIA_PRODUCTO_TB(CATEGORIA_PRODUCTO_ID_CATEGORIA_PK),
    CONSTRAINT PRODUCTO_ESTADOS_ID_ESTADO_PK_FK FOREIGN KEY (ESTADOS_ID_ESTADO_PK)
        REFERENCES FIDE_ESTADOS_TB(ESTADOS_ID_ESTADO_PK)
);

CREATE TABLE FIDE_SERVICIOS_TB (
    SERVICIOS_ID_SERVICIO_PK NUMBER CONSTRAINT SERVICIOS_ID_SERVICIO_PK PRIMARY KEY,
    nombre VARCHAR2(100),
    descripcion VARCHAR2(255),
    precio NUMBER(12,2),
    CATEGORIA_SERVICIO_ID_CATEGORIA_PK NUMBER,
    ESTADOS_ID_ESTADO_PK NUMBER,
    CONSTRAINT SERVICIO_CATEGORIA_ID_CATEGORIA_PK_FK FOREIGN KEY (CATEGORIA_SERVICIO_ID_CATEGORIA_PK)
        REFERENCES FIDE_CATEGORIA_SERVICIO_TB(CATEGORIA_SERVICIO_ID_CATEGORIA_PK),
    CONSTRAINT SERVICIO_ESTADOS_ID_ESTADO_PK_FK FOREIGN KEY (ESTADOS_ID_ESTADO_PK)
        REFERENCES FIDE_ESTADOS_TB(ESTADOS_ID_ESTADO_PK)
);

CREATE TABLE FIDE_PAGOS_TB (
    PAGOS_ID_PAGO_PK NUMBER CONSTRAINT PAGOS_ID_PAGO_PK PRIMARY KEY,
    fecha_pago DATE,
    monto NUMBER(12,2),
    METODO_PAGO_ID_METODO_PK NUMBER,
    ESTADOS_ID_ESTADO_PK NUMBER,
    CONSTRAINT PAGOS_METODO_PAGO_ID_METODO_PK_FK FOREIGN KEY (METODO_PAGO_ID_METODO_PK)
        REFERENCES FIDE_METODO_PAGO_TB(METODO_PAGO_ID_METODO_PK),
    CONSTRAINT PAGOS_ESTADOS_ID_ESTADO_PK_FK FOREIGN KEY (ESTADOS_ID_ESTADO_PK)
        REFERENCES FIDE_ESTADOS_TB(ESTADOS_ID_ESTADO_PK)
);


--------------------------------------------------------------------------
-- 3. TABLAS DE ALTO NIVEL (CLIENTES, EMPLEADOS, DIRECCIONES, RESERVACIONES)
--------------------------------------------------------------------------

CREATE TABLE FIDE_CLIENTES_TB (
    USUARIOS_ID_CEDULA_PK VARCHAR2(20) CONSTRAINT CLIENTES_USUARIOS_ID_CEDULA_PK PRIMARY KEY,
    telefono VARCHAR2(20),
    CONSTRAINT CLIENTES_USUARIOS_ID_CEDULA_PK_FK FOREIGN KEY (USUARIOS_ID_CEDULA_PK)
        REFERENCES FIDE_USUARIOS_TB(USUARIOS_ID_CEDULA_PK)
);

CREATE TABLE FIDE_EMPLEADOS_TB (
    USUARIOS_ID_CEDULA_PK VARCHAR2(20) CONSTRAINT EMPLEADOS_USUARIOS_ID_CEDULA_PK PRIMARY KEY,
    puesto VARCHAR2(100),
    fecha_contratacion DATE,
    CONSTRAINT EMPLEADOS_USUARIOS_ID_CEDULA_PK_FK FOREIGN KEY (USUARIOS_ID_CEDULA_PK)
        REFERENCES FIDE_USUARIOS_TB(USUARIOS_ID_CEDULA_PK)
);

CREATE TABLE FIDE_CORREO_TB (
    CORREO_ID_CORREO_PK NUMBER CONSTRAINT CORREO_ID_CORREO_PK PRIMARY KEY,
    correo_electronico VARCHAR2(150),
    tipo_correo VARCHAR2(50),
    USUARIOS_ID_CEDULA_PK VARCHAR2(20),
    -- [MODIFICACIÓN 8] Se agrega la columna de estado para borrado lógico
    ESTADOS_ID_ESTADO_FK NUMBER DEFAULT 1,
    CONSTRAINT CORREO_USUARIOS_ID_CEDULA_PK_FK FOREIGN KEY (USUARIOS_ID_CEDULA_PK)
        REFERENCES FIDE_USUARIOS_TB(USUARIOS_ID_CEDULA_PK),
    CONSTRAINT CORREO_ESTADOS_FK FOREIGN KEY (ESTADOS_ID_ESTADO_FK)
        REFERENCES FIDE_ESTADOS_TB(ESTADOS_ID_ESTADO_PK)
);

CREATE TABLE FIDE_DIRECCIONES_TB (
    DIRECCIONES_ID_DIRECCION_PK NUMBER CONSTRAINT DIRECCIONES_ID_DIRECCION_PK PRIMARY KEY,
    DISTRITO_ID_DISTRITO_PK NUMBER,
    USUARIOS_ID_CEDULA_PK VARCHAR2(20),
    descripcion VARCHAR2(255),
    -- [MODIFICACIÓN 9] Se agrega la columna de estado para borrado lógico (se sigue usando PK por consistencia original de esta tabla)
    ESTADOS_ID_ESTADO_PK NUMBER DEFAULT 1,
    CONSTRAINT DIRECCIONES_DISTRITO_ID_DISTRITO_PK_FK FOREIGN KEY (DISTRITO_ID_DISTRITO_PK)
        REFERENCES FIDE_DISTRITO_TB(DISTRITO_ID_DISTRITO_PK),
    CONSTRAINT DIRECCIONES_USUARIOS_ID_CEDULA_PK_FK FOREIGN KEY (USUARIOS_ID_CEDULA_PK)
        REFERENCES FIDE_USUARIOS_TB(USUARIOS_ID_CEDULA_PK),
    CONSTRAINT DIRECCIONES_ESTADOS_PK_FK FOREIGN KEY (ESTADOS_ID_ESTADO_PK)
        REFERENCES FIDE_ESTADOS_TB(ESTADOS_ID_ESTADO_PK)
);

CREATE TABLE FIDE_RESERVACIONES_TB (
    RESERVACIONES_ID_RESERVACION_PK NUMBER CONSTRAINT RESERVACIONES_ID_RESERVACION_PK PRIMARY KEY,
    fecha_reservacion DATE,
    hora_inicio TIMESTAMP,
    hora_fin TIMESTAMP,
    ESTADOS_ID_ESTADO_PK NUMBER,
    USUARIOS_ID_CEDULA_PK VARCHAR2(20),
    DIRECCIONES_ID_DIRECCION_PK NUMBER,
    CONSTRAINT RESERVACIONES_ESTADOS_ID_ESTADO_PK_FK FOREIGN KEY (ESTADOS_ID_ESTADO_PK)
        REFERENCES FIDE_ESTADOS_TB(ESTADOS_ID_ESTADO_PK),
    CONSTRAINT RESERVACIONES_USUARIOS_ID_CEDULA_PK_FK FOREIGN KEY (USUARIOS_ID_CEDULA_PK)
        REFERENCES FIDE_USUARIOS_TB(USUARIOS_ID_CEDULA_PK),
    CONSTRAINT RESERVACIONES_DIRECCIONES_ID_DIRECCION_PK_FK FOREIGN KEY (DIRECCIONES_ID_DIRECCION_PK)
        REFERENCES FIDE_DIRECCIONES_TB(DIRECCIONES_ID_DIRECCION_PK)
);


--------------------------------------------------------------------------
-- 4. TABLAS FINALES (DETALLES Y FACTURACIÓN)
--------------------------------------------------------------------------

CREATE TABLE FIDE_PAQUETES_POR_SERVICIO_TB (
    PAQUETE_ID_PAQUETE_PK NUMBER,
    SERVICIOS_ID_SERVICIO_PK NUMBER,
    CONSTRAINT PK_PAQ_SERV PRIMARY KEY (PAQUETE_ID_PAQUETE_PK, SERVICIOS_ID_SERVICIO_PK),
    CONSTRAINT PPS_PAQUETE_ID_PAQUETE_PK_FK FOREIGN KEY (PAQUETE_ID_PAQUETE_PK)
        REFERENCES FIDE_PAQUETE_TB(PAQUETE_ID_PAQUETE_PK),
    CONSTRAINT PPS_SERVICIOS_ID_SERVICIO_PK_FK FOREIGN KEY (SERVICIOS_ID_SERVICIO_PK)
        REFERENCES FIDE_SERVICIOS_TB(SERVICIOS_ID_SERVICIO_PK)
);

CREATE TABLE FIDE_ASIGNACION_TB (
    ASIGNACION_ID_ASIGNACION_PK NUMBER CONSTRAINT ASIGNACION_ID_ASIGNACION_PK PRIMARY KEY,
    Notas VARCHAR2(400),
    PRODUCTO_ID_PRODUCTO_PK NUMBER,
    RESERVACIONES_ID_RESERVACION_PK NUMBER,
    CONSTRAINT ASIGNACION_PRODUCTO_ID_PRODUCTO_PK_FK FOREIGN KEY (PRODUCTO_ID_PRODUCTO_PK)
        REFERENCES FIDE_PRODUCTOS_TB(PRODUCTO_ID_PRODUCTO_PK),
    CONSTRAINT ASIGNACION_RESERVACIONES_ID_RESERVACION_PK_FK FOREIGN KEY (RESERVACIONES_ID_RESERVACION_PK)
        REFERENCES FIDE_RESERVACIONES_TB(RESERVACIONES_ID_RESERVACION_PK)
);

CREATE TABLE FIDE_DETALLE_RESERVACION_TB (
    DETALLE_RESERVACION_ID_PK NUMBER CONSTRAINT DETALLE_RESERVACION_ID_PK PRIMARY KEY,
    cantidad NUMBER,
    precio_unitario NUMBER(12,2),
    SERVICIOS_ID_SERVICIO_PK NUMBER,
    RESERVACIONES_ID_RESERVACION_PK NUMBER,
    PAQUETE_ID_PAQUETE_PK NUMBER,
    
    CONSTRAINT DET_RES_SERVICIOS_ID_SERVICIO_PK_FK FOREIGN KEY (SERVICIOS_ID_SERVICIO_PK)
        REFERENCES FIDE_SERVICIOS_TB(SERVICIOS_ID_SERVICIO_PK),
    CONSTRAINT DET_RES_RESERVACIONES_ID_RESERVACION_PK_FK FOREIGN KEY (RESERVACIONES_ID_RESERVACION_PK)
        REFERENCES FIDE_RESERVACIONES_TB(RESERVACIONES_ID_RESERVACION_PK),
    CONSTRAINT DET_RES_PAQUETE_ID_PAQUETE_PK_FK FOREIGN KEY (PAQUETE_ID_PAQUETE_PK)
        REFERENCES FIDE_PAQUETE_TB(PAQUETE_ID_PAQUETE_PK)
);

CREATE TABLE FIDE_FACTURACION_TB (
    FACTURACION_ID_NUMERO_FACTURA_PK NUMBER CONSTRAINT FACTURACION_ID_NUMERO_FACTURA_PK PRIMARY KEY,
    fecha_emision DATE,
    monto_total NUMBER(12,2),
    impuestos NUMBER(12,2),
    destalle_factura VARCHAR2(255),
    PAGOS_ID_PAGO_PK NUMBER,
    ESTADOS_ID_ESTADO_PK NUMBER,
    RESERVACIONES_ID_RESERVACION_PK NUMBER,
    CONSTRAINT FACTURACION_PAGOS_ID_PAGO_PK_FK FOREIGN KEY (PAGOS_ID_PAGO_PK)
        REFERENCES FIDE_PAGOS_TB(PAGOS_ID_PAGO_PK),
    CONSTRAINT FACTURACION_ESTADOS_ID_ESTADO_PK_FK FOREIGN KEY (ESTADOS_ID_ESTADO_PK)
        REFERENCES FIDE_ESTADOS_TB(ESTADOS_ID_ESTADO_PK),
    CONSTRAINT FACTURACION_RESERVACIONES_ID_RESERVACION_PK_FK FOREIGN KEY (RESERVACIONES_ID_RESERVACION_PK)
        REFERENCES FIDE_RESERVACIONES_TB(RESERVACIONES_ID_RESERVACION_PK)
);

CREATE TABLE FIDE_DETALLE_FACTURA_TB (
    DETALLE_FACTURA_ID_DETALLE_PK NUMBER CONSTRAINT DETALLE_FACTURA_ID_DETALLE_PK PRIMARY KEY,
    cantidad NUMBER,
    precio_unitario NUMBER(12,2),
    subtotal_linea NUMBER(12,2),
    FACTURACION_ID_NUMERO_FACTURA_FK NUMBER,
    CONSTRAINT DETALLE_FACTURA_ID_NUMERO_FACTURA_FK FOREIGN KEY (FACTURACION_ID_NUMERO_FACTURA_FK)
        REFERENCES FIDE_FACTURACION_TB(FACTURACION_ID_NUMERO_FACTURA_PK)
);

COMMIT;


-- ==========================================================================
-- REESTRUCTURACIÓN PARA LLAVES COMPUESTAS Y TRAZABILIDAD
-- ==========================================================================

-- 1. ELIMINAR TABLAS CONFLICTIVAS (En orden por dependencias)
DROP TABLE FIDE_DETALLE_FACTURA_TB CASCADE CONSTRAINTS;
DROP TABLE FIDE_DETALLE_RESERVACION_TB CASCADE CONSTRAINTS;

-- 2. RE-CREAR FIDE_DETALLE_RESERVACION_TB (Con Llave Compuesta)
-- Objetivo: Que el detalle pertenezca existencialmente a la reserva.
CREATE TABLE FIDE_DETALLE_RESERVACION_TB (
    RESERVACIONES_ID_RESERVACION_PK NUMBER, -- Parte 1 de la PK
    NUMERO_LINEA NUMBER,                    -- Parte 2 de la PK (Consecutivo 1, 2, 3 por reserva)
    cantidad NUMBER,
    precio_unitario NUMBER(12,2),
    SERVICIOS_ID_SERVICIO_PK NUMBER,
    PAQUETE_ID_PAQUETE_PK NUMBER,
    
    -- Definición de la Llave Compuesta
    CONSTRAINT PK_DETALLE_RESERVACION PRIMARY KEY (RESERVACIONES_ID_RESERVACION_PK, NUMERO_LINEA),
    
    -- Foreign Keys
    CONSTRAINT DET_RES_RESERVA_FK FOREIGN KEY (RESERVACIONES_ID_RESERVACION_PK)
        REFERENCES FIDE_RESERVACIONES_TB(RESERVACIONES_ID_RESERVACION_PK),
    CONSTRAINT DET_RES_SERVICIO_FK FOREIGN KEY (SERVICIOS_ID_SERVICIO_PK)
        REFERENCES FIDE_SERVICIOS_TB(SERVICIOS_ID_SERVICIO_PK),
    CONSTRAINT DET_RES_PAQUETE_FK FOREIGN KEY (PAQUETE_ID_PAQUETE_PK)
        REFERENCES FIDE_PAQUETE_TB(PAQUETE_ID_PAQUETE_PK)
);

-- 3. RE-CREAR FIDE_DETALLE_FACTURA_TB (Con Llave Compuesta y Relación a Servicio)
-- Objetivo: Vincular cada linea de cobro con el servicio real y usar llave compuesta.
CREATE TABLE FIDE_DETALLE_FACTURA_TB (
    FACTURACION_ID_NUMERO_FACTURA_FK NUMBER, -- Parte 1 de la PK
    NUMERO_LINEA NUMBER,                     -- Parte 2 de la PK
    cantidad NUMBER,
    precio_unitario NUMBER(12,2),
    subtotal_linea NUMBER(12,2),
    
    -- [CORRECCIÓN IMPORTANTE] Relación directa con el Servicio facturado
    SERVICIOS_ID_SERVICIO_PK NUMBER, 
    
    -- Definición de la Llave Compuesta
    CONSTRAINT PK_DETALLE_FACTURA PRIMARY KEY (FACTURACION_ID_NUMERO_FACTURA_FK, NUMERO_LINEA),
    
    -- Foreign Keys
    CONSTRAINT DET_FACT_FACTURA_FK FOREIGN KEY (FACTURACION_ID_NUMERO_FACTURA_FK)
        REFERENCES FIDE_FACTURACION_TB(FACTURACION_ID_NUMERO_FACTURA_PK),
    CONSTRAINT DET_FACT_SERVICIO_FK FOREIGN KEY (SERVICIOS_ID_SERVICIO_PK)
        REFERENCES FIDE_SERVICIOS_TB(SERVICIOS_ID_SERVICIO_PK)
);

COMMIT;
