SET SERVEROUTPUT ON;

-- ==========================================================================
-- PASO 1: INSERCIÓN DE DATOS BASE (Sin Dependencias Externas)
-- ==========================================================================

-- FIDE_ESTADOS_TB (Clave primaria: ESTADOS_ID_ESTADO_PK)
BEGIN
    FIDE_PROYECTO_FINAL_PKG.FIDE_ESTADOS_INSERTAR_SP (1, 'General', 'Activo');
    FIDE_PROYECTO_FINAL_PKG.FIDE_ESTADOS_INSERTAR_SP (2, 'General', 'Inactivo/Anulado');
    FIDE_PROYECTO_FINAL_PKG.FIDE_ESTADOS_INSERTAR_SP (3, 'Reservacion', 'Pendiente');
    FIDE_PROYECTO_FINAL_PKG.FIDE_ESTADOS_INSERTAR_SP (4, 'Reservacion', 'Completada');
    FIDE_PROYECTO_FINAL_PKG.FIDE_ESTADOS_INSERTAR_SP (5, 'Reservacion', 'Cancelada');
    FIDE_PROYECTO_FINAL_PKG.FIDE_ESTADOS_INSERTAR_SP (6, 'Facturacion/Pago', 'Pagado');
END;
/

-- FIDE_ROLES_TB (Clave primaria: ROLES_ID_ROL_PK)
BEGIN
    FIDE_PROYECTO_FINAL_PKG.FIDE_ROLES_INSERTAR_SP (10, 'Administrador', 'Control total del sistema.');
    FIDE_PROYECTO_FINAL_PKG.FIDE_ROLES_INSERTAR_SP (20, 'Empleado', 'Gestión de servicios y productos.');
    FIDE_PROYECTO_FINAL_PKG.FIDE_ROLES_INSERTAR_SP (30, 'Cliente', 'Acceso a historial y reservas.');
    FIDE_PROYECTO_FINAL_PKG.FIDE_ROLES_INSERTAR_SP (40, 'Invitado', 'Acceso limitado sin transacciones.');
END;
/

-- FIDE_METODO_PAGO_TB (Clave primaria: METODO_PAGO_ID_METODO_PK)
BEGIN
    FIDE_PROYECTO_FINAL_PKG.FIDE_METODO_PAGO_INSERTAR_SP (100, 'Tarjeta de Crédito');
    FIDE_PROYECTO_FINAL_PKG.FIDE_METODO_PAGO_INSERTAR_SP (101, 'Transferencia SINPE');
    FIDE_PROYECTO_FINAL_PKG.FIDE_METODO_PAGO_INSERTAR_SP (102, 'Efectivo');
    FIDE_PROYECTO_FINAL_PKG.FIDE_METODO_PAGO_INSERTAR_SP (103, 'Billetera Digital');
END;
/

-- ==========================================================================
-- PASO 2: INSERCIÓN DE DATOS GEOGRÁFICOS (Limitado a 7 Provincias)
-- ==========================================================================

-- FIDE_PROVINCIA_TB (Clave primaria: PROVINCIA_ID_PROVINCIA_PK)
BEGIN
    FIDE_PROYECTO_FINAL_PKG.FIDE_PROVINCIA_INSERTAR_SP (1, 'San José');
    FIDE_PROYECTO_FINAL_PKG.FIDE_PROVINCIA_INSERTAR_SP (2, 'Alajuela');
    FIDE_PROYECTO_FINAL_PKG.FIDE_PROVINCIA_INSERTAR_SP (3, 'Cartago');
    FIDE_PROYECTO_FINAL_PKG.FIDE_PROVINCIA_INSERTAR_SP (4, 'Heredia');
    FIDE_PROYECTO_FINAL_PKG.FIDE_PROVINCIA_INSERTAR_SP (5, 'Guanacaste');
    FIDE_PROYECTO_FINAL_PKG.FIDE_PROVINCIA_INSERTAR_SP (6, 'Puntarenas');
    FIDE_PROYECTO_FINAL_PKG.FIDE_PROVINCIA_INSERTAR_SP (7, 'Limón');
END;
/

-- FIDE_CANTON_TB (Clave primaria: CANTON_ID_CANTON_PK)
BEGIN
    -- San José (1)
    FIDE_PROYECTO_FINAL_PKG.FIDE_CANTON_INSERTAR_SP (101, 1, 'San José');
    FIDE_PROYECTO_FINAL_PKG.FIDE_CANTON_INSERTAR_SP (102, 1, 'Escazú');
    -- Alajuela (2)
    FIDE_PROYECTO_FINAL_PKG.FIDE_CANTON_INSERTAR_SP (201, 2, 'Alajuela');
    FIDE_PROYECTO_FINAL_PKG.FIDE_CANTON_INSERTAR_SP (202, 2, 'San Ramón');
    -- Cartago (3)
    FIDE_PROYECTO_FINAL_PKG.FIDE_CANTON_INSERTAR_SP (301, 3, 'Cartago');
END;
/

-- FIDE_DISTRITO_TB (Clave primaria: DISTRITO_ID_DISTRITO_PK)
BEGIN
    -- San José (101)
    FIDE_PROYECTO_FINAL_PKG.FIDE_DISTRITO_INSERTAR_SP (10101, 101, 'Carmen');
    FIDE_PROYECTO_FINAL_PKG.FIDE_DISTRITO_INSERTAR_SP (10102, 101, 'Merced');
    -- Escazú (102)
    FIDE_PROYECTO_FINAL_PKG.FIDE_DISTRITO_INSERTAR_SP (10201, 102, 'Escazú');
    -- Alajuela (201)
    FIDE_PROYECTO_FINAL_PKG.FIDE_DISTRITO_INSERTAR_SP (20101, 201, 'Alajuela');
    -- Cartago (301)
    FIDE_PROYECTO_FINAL_PKG.FIDE_DISTRITO_INSERTAR_SP (30101, 301, 'Oriental');
    FIDE_PROYECTO_FINAL_PKG.FIDE_DISTRITO_INSERTAR_SP (30102, 301, 'Occidental');
END;
/


SET SERVEROUTPUT ON;

BEGIN
    -- -------------------------------------------------------------------------
    -- CLIENTE 1: Juan Pérez
    -- -------------------------------------------------------------------------
    FIDE_PROYECTO_FINAL_PKG.FIDE_USUARIOS_INSERTAR_SP('101110111', 'Juan', 'Pérez', 'Castro', 'Pass123!', 30);
    FIDE_PROYECTO_FINAL_PKG.FIDE_CLIENTES_INSERTAR_SP('101110111', '8801-0001');

    -- CLIENTE 2: María Rodríguez
    FIDE_PROYECTO_FINAL_PKG.FIDE_USUARIOS_INSERTAR_SP('102220222', 'María', 'Rodríguez', 'Solís', 'Pass123!', 30);
    FIDE_PROYECTO_FINAL_PKG.FIDE_CLIENTES_INSERTAR_SP('102220222', '8802-0002');

    -- CLIENTE 3: Carlos González
    FIDE_PROYECTO_FINAL_PKG.FIDE_USUARIOS_INSERTAR_SP('103330333', 'Carlos', 'González', 'Mora', 'Pass123!', 30);
    FIDE_PROYECTO_FINAL_PKG.FIDE_CLIENTES_INSERTAR_SP('103330333', '8803-0003');

    -- CLIENTE 4: Ana Vargas
    FIDE_PROYECTO_FINAL_PKG.FIDE_USUARIOS_INSERTAR_SP('104440444', 'Ana', 'Vargas', 'Rojas', 'Pass123!', 30);
    FIDE_PROYECTO_FINAL_PKG.FIDE_CLIENTES_INSERTAR_SP('104440444', '8804-0004');

    -- CLIENTE 5: Luis Jiménez
    FIDE_PROYECTO_FINAL_PKG.FIDE_USUARIOS_INSERTAR_SP('105550555', 'Luis', 'Jiménez', 'Salazar', 'Pass123!', 30);
    FIDE_PROYECTO_FINAL_PKG.FIDE_CLIENTES_INSERTAR_SP('105550555', '8805-0005');

    -- CLIENTE 6: Elena Castro
    FIDE_PROYECTO_FINAL_PKG.FIDE_USUARIOS_INSERTAR_SP('201110111', 'Elena', 'Castro', 'Méndez', 'Pass123!', 30);
    FIDE_PROYECTO_FINAL_PKG.FIDE_CLIENTES_INSERTAR_SP('201110111', '8806-0006');

    -- CLIENTE 7: Pedro Fernández
    FIDE_PROYECTO_FINAL_PKG.FIDE_USUARIOS_INSERTAR_SP('202220222', 'Pedro', 'Fernández', 'Quirós', 'Pass123!', 30);
    FIDE_PROYECTO_FINAL_PKG.FIDE_CLIENTES_INSERTAR_SP('202220222', '8807-0007');

    -- CLIENTE 8: Laura Ramírez
    FIDE_PROYECTO_FINAL_PKG.FIDE_USUARIOS_INSERTAR_SP('203330333', 'Laura', 'Ramírez', 'López', 'Pass123!', 30);
    FIDE_PROYECTO_FINAL_PKG.FIDE_CLIENTES_INSERTAR_SP('203330333', '8808-0008');

    -- CLIENTE 9: Jorge Herrera
    FIDE_PROYECTO_FINAL_PKG.FIDE_USUARIOS_INSERTAR_SP('204440444', 'Jorge', 'Herrera', 'Sánchez', 'Pass123!', 30);
    FIDE_PROYECTO_FINAL_PKG.FIDE_CLIENTES_INSERTAR_SP('204440444', '8809-0009');

    -- CLIENTE 10: Sofía Araya
    FIDE_PROYECTO_FINAL_PKG.FIDE_USUARIOS_INSERTAR_SP('205550555', 'Sofía', 'Araya', 'Monge', 'Pass123!', 30);
    FIDE_PROYECTO_FINAL_PKG.FIDE_CLIENTES_INSERTAR_SP('205550555', '8810-0010');

    -- CLIENTE 11: Diego Cordero
    FIDE_PROYECTO_FINAL_PKG.FIDE_USUARIOS_INSERTAR_SP('301110111', 'Diego', 'Cordero', 'Brenes', 'Pass123!', 30);
    FIDE_PROYECTO_FINAL_PKG.FIDE_CLIENTES_INSERTAR_SP('301110111', '8811-0011');

    -- CLIENTE 12: Valentina Valverde
    FIDE_PROYECTO_FINAL_PKG.FIDE_USUARIOS_INSERTAR_SP('302220222', 'Valentina', 'Valverde', 'Mora', 'Pass123!', 30);
    FIDE_PROYECTO_FINAL_PKG.FIDE_CLIENTES_INSERTAR_SP('302220222', '8812-0012');

    -- CLIENTE 13: Andrés Murillo
    FIDE_PROYECTO_FINAL_PKG.FIDE_USUARIOS_INSERTAR_SP('303330333', 'Andrés', 'Murillo', 'Rojas', 'Pass123!', 30);
    FIDE_PROYECTO_FINAL_PKG.FIDE_CLIENTES_INSERTAR_SP('303330333', '8813-0013');

    -- CLIENTE 14: Camila Navarro
    FIDE_PROYECTO_FINAL_PKG.FIDE_USUARIOS_INSERTAR_SP('304440444', 'Camila', 'Navarro', 'Cruz', 'Pass123!', 30);
    FIDE_PROYECTO_FINAL_PKG.FIDE_CLIENTES_INSERTAR_SP('304440444', '8814-0014');

    -- CLIENTE 15: Gabriel Solano
    FIDE_PROYECTO_FINAL_PKG.FIDE_USUARIOS_INSERTAR_SP('305550555', 'Gabriel', 'Solano', 'Campos', 'Pass123!', 30);
    FIDE_PROYECTO_FINAL_PKG.FIDE_CLIENTES_INSERTAR_SP('305550555', '8815-0015');

    -- CLIENTE 16: Daniela Madrigal
    FIDE_PROYECTO_FINAL_PKG.FIDE_USUARIOS_INSERTAR_SP('401110111', 'Daniela', 'Madrigal', 'Vega', 'Pass123!', 30);
    FIDE_PROYECTO_FINAL_PKG.FIDE_CLIENTES_INSERTAR_SP('401110111', '8816-0016');

    -- CLIENTE 17: Ricardo Mora
    FIDE_PROYECTO_FINAL_PKG.FIDE_USUARIOS_INSERTAR_SP('402220222', 'Ricardo', 'Mora', 'Salas', 'Pass123!', 30);
    FIDE_PROYECTO_FINAL_PKG.FIDE_CLIENTES_INSERTAR_SP('402220222', '8817-0017');

    -- CLIENTE 18: Mariana Calvo
    FIDE_PROYECTO_FINAL_PKG.FIDE_USUARIOS_INSERTAR_SP('403330333', 'Mariana', 'Calvo', 'Alfaro', 'Pass123!', 30);
    FIDE_PROYECTO_FINAL_PKG.FIDE_CLIENTES_INSERTAR_SP('403330333', '8818-0018');

    -- CLIENTE 19: Felipe Quesada
    FIDE_PROYECTO_FINAL_PKG.FIDE_USUARIOS_INSERTAR_SP('404440444', 'Felipe', 'Quesada', 'Chaves', 'Pass123!', 30);
    FIDE_PROYECTO_FINAL_PKG.FIDE_CLIENTES_INSERTAR_SP('404440444', '8819-0019');

    -- CLIENTE 20: Natalia Zúñiga
    FIDE_PROYECTO_FINAL_PKG.FIDE_USUARIOS_INSERTAR_SP('405550555', 'Natalia', 'Zúñiga', 'Gutiérrez', 'Pass123!', 30);
    FIDE_PROYECTO_FINAL_PKG.FIDE_CLIENTES_INSERTAR_SP('405550555', '8820-0020');

    DBMS_OUTPUT.PUT_LINE('=== Carga de 20 Clientes completada exitosamente ===');
END;





select * from FIDE_DISTRITO_tb