--- Secuencias
CREATE SEQUENCE FIDE_ESTADOS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FIDE_ROLES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FIDE_PROVINCIA_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FIDE_METODO_PAGO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FIDE_CAT_PROD_SEQ START WITH 1 INCREMENT BY 1; 
CREATE SEQUENCE FIDE_CAT_SERV_SEQ START WITH 1 INCREMENT BY 1; 
CREATE SEQUENCE FIDE_PAQUETE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FIDE_CANTON_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FIDE_DISTRITO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FIDE_PRODUCTOS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FIDE_SERVICIOS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FIDE_PAGOS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FIDE_CORREO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FIDE_DIRECCIONES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FIDE_RESERVACIONES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FIDE_ASIGNACION_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FIDE_FACTURACION_SEQ START WITH 1 INCREMENT BY 1;


--- ==========================================================================
---- FUNCION Y TRIGGERS                                 
--- ========================================================================== 

-- Función Compuesta
CREATE OR REPLACE FUNCTION FIDE_SEQUENCIA_ALFANUMERICA_FN 
RETURN VARCHAR2 IS
    V_FECHA VARCHAR2(10);
    V_NUMERO VARCHAR2(10);
    V_LETRA CHAR(1);
BEGIN
    V_FECHA := TO_CHAR(SYSDATE, 'YYYYMMDD');
    V_NUMERO := LPAD(FIDE_FACTURACION_SEQ.NEXTVAL, 5, '0');
    V_LETRA := CHR(TRUNC(DBMS_RANDOM.VALUE(65, 91)));
    RETURN V_FECHA || '-' || V_NUMERO || '-' || V_LETRA;
END;
/

-- Triggers 
CREATE OR REPLACE TRIGGER FIDE_ESTADOS_TRG BEFORE INSERT OR UPDATE ON FIDE_ESTADOS_TB FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.ESTADOS_ID_ESTADO_PK IS NULL THEN :NEW.ESTADOS_ID_ESTADO_PK := FIDE_ESTADOS_SEQ.NEXTVAL; END IF;
        :NEW.CREADO_POR := USER; :NEW.FECHA_CREACION := SYSTIMESTAMP; :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.MODIFICADO_POR := USER; :NEW.FECHA_MODIFICACION := SYSTIMESTAMP; :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_ROLES_TRG BEFORE INSERT OR UPDATE ON FIDE_ROLES_TB FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.ROLES_ID_ROL_PK IS NULL THEN :NEW.ROLES_ID_ROL_PK := FIDE_ROLES_SEQ.NEXTVAL; END IF;
        :NEW.CREADO_POR := USER; :NEW.FECHA_CREACION := SYSTIMESTAMP; :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.MODIFICADO_POR := USER; :NEW.FECHA_MODIFICACION := SYSTIMESTAMP; :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_PROVINCIA_TRG BEFORE INSERT OR UPDATE ON FIDE_PROVINCIA_TB FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.PROVINCIA_ID_PROVINCIA_PK IS NULL THEN :NEW.PROVINCIA_ID_PROVINCIA_PK := FIDE_PROVINCIA_SEQ.NEXTVAL; END IF;
        :NEW.CREADO_POR := USER; :NEW.FECHA_CREACION := SYSTIMESTAMP; :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.MODIFICADO_POR := USER; :NEW.FECHA_MODIFICACION := SYSTIMESTAMP; :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_METODO_PAGO_TRG BEFORE INSERT OR UPDATE ON FIDE_METODO_PAGO_TB FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.METODO_PAGO_ID_METODO_PK IS NULL THEN :NEW.METODO_PAGO_ID_METODO_PK := FIDE_METODO_PAGO_SEQ.NEXTVAL; END IF;
        :NEW.CREADO_POR := USER; :NEW.FECHA_CREACION := SYSTIMESTAMP; :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.MODIFICADO_POR := USER; :NEW.FECHA_MODIFICACION := SYSTIMESTAMP; :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_CAT_PROD_TRG BEFORE INSERT OR UPDATE ON FIDE_CATEGORIA_PRODUCTO_TB FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.CATEGORIA_PRODUCTO_ID_CATEGORIA_PK IS NULL THEN :NEW.CATEGORIA_PRODUCTO_ID_CATEGORIA_PK := FIDE_CAT_PROD_SEQ.NEXTVAL; END IF;
        :NEW.CREADO_POR := USER; :NEW.FECHA_CREACION := SYSTIMESTAMP; :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.MODIFICADO_POR := USER; :NEW.FECHA_MODIFICACION := SYSTIMESTAMP; :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_CAT_SERV_TRG BEFORE INSERT OR UPDATE ON FIDE_CATEGORIA_SERVICIO_TB FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.CATEGORIA_SERVICIO_ID_CATEGORIA_PK IS NULL THEN :NEW.CATEGORIA_SERVICIO_ID_CATEGORIA_PK := FIDE_CAT_SERV_SEQ.NEXTVAL; END IF;
        :NEW.CREADO_POR := USER; :NEW.FECHA_CREACION := SYSTIMESTAMP; :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.MODIFICADO_POR := USER; :NEW.FECHA_MODIFICACION := SYSTIMESTAMP; :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_PAQUETE_TRG BEFORE INSERT OR UPDATE ON FIDE_PAQUETE_TB FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.PAQUETE_ID_PAQUETE_PK IS NULL THEN :NEW.PAQUETE_ID_PAQUETE_PK := FIDE_PAQUETE_SEQ.NEXTVAL; END IF;
        :NEW.CREADO_POR := USER; :NEW.FECHA_CREACION := SYSTIMESTAMP; :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.MODIFICADO_POR := USER; :NEW.FECHA_MODIFICACION := SYSTIMESTAMP; :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_CANTON_TRG BEFORE INSERT OR UPDATE ON FIDE_CANTON_TB FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.CANTON_ID_CANTON_PK IS NULL THEN :NEW.CANTON_ID_CANTON_PK := FIDE_CANTON_SEQ.NEXTVAL; END IF;
        :NEW.CREADO_POR := USER; :NEW.FECHA_CREACION := SYSTIMESTAMP; :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.MODIFICADO_POR := USER; :NEW.FECHA_MODIFICACION := SYSTIMESTAMP; :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_DISTRITO_TRG BEFORE INSERT OR UPDATE ON FIDE_DISTRITO_TB FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.DISTRITO_ID_DISTRITO_PK IS NULL THEN :NEW.DISTRITO_ID_DISTRITO_PK := FIDE_DISTRITO_SEQ.NEXTVAL; END IF;
        :NEW.CREADO_POR := USER; :NEW.FECHA_CREACION := SYSTIMESTAMP; :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.MODIFICADO_POR := USER; :NEW.FECHA_MODIFICACION := SYSTIMESTAMP; :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_USUARIOS_TRG BEFORE INSERT OR UPDATE ON FIDE_USUARIOS_TB FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER; :NEW.FECHA_CREACION := SYSTIMESTAMP; :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.MODIFICADO_POR := USER; :NEW.FECHA_MODIFICACION := SYSTIMESTAMP; :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_PRODUCTOS_TRG BEFORE INSERT OR UPDATE ON FIDE_PRODUCTOS_TB FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.PRODUCTO_ID_PRODUCTO_PK IS NULL THEN :NEW.PRODUCTO_ID_PRODUCTO_PK := FIDE_PRODUCTOS_SEQ.NEXTVAL; END IF;
        :NEW.CREADO_POR := USER; :NEW.FECHA_CREACION := SYSTIMESTAMP; :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.MODIFICADO_POR := USER; :NEW.FECHA_MODIFICACION := SYSTIMESTAMP; :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_SERVICIOS_TRG BEFORE INSERT OR UPDATE ON FIDE_SERVICIOS_TB FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.SERVICIOS_ID_SERVICIO_PK IS NULL THEN :NEW.SERVICIOS_ID_SERVICIO_PK := FIDE_SERVICIOS_SEQ.NEXTVAL; END IF;
        :NEW.CREADO_POR := USER; :NEW.FECHA_CREACION := SYSTIMESTAMP; :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.MODIFICADO_POR := USER; :NEW.FECHA_MODIFICACION := SYSTIMESTAMP; :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_PAGOS_TRG BEFORE INSERT OR UPDATE ON FIDE_PAGOS_TB FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.PAGOS_ID_PAGO_PK IS NULL THEN :NEW.PAGOS_ID_PAGO_PK := FIDE_PAGOS_SEQ.NEXTVAL; END IF;
        :NEW.CREADO_POR := USER; :NEW.FECHA_CREACION := SYSTIMESTAMP; :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.MODIFICADO_POR := USER; :NEW.FECHA_MODIFICACION := SYSTIMESTAMP; :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_CLIENTES_TRG BEFORE INSERT OR UPDATE ON FIDE_CLIENTES_TB FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER; :NEW.FECHA_CREACION := SYSTIMESTAMP; :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.MODIFICADO_POR := USER; :NEW.FECHA_MODIFICACION := SYSTIMESTAMP; :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_EMPLEADOS_TRG BEFORE INSERT OR UPDATE ON FIDE_EMPLEADOS_TB FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER; :NEW.FECHA_CREACION := SYSTIMESTAMP; :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.MODIFICADO_POR := USER; :NEW.FECHA_MODIFICACION := SYSTIMESTAMP; :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_CORREO_TRG BEFORE INSERT OR UPDATE ON FIDE_CORREO_TB FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.CORREO_ID_CORREO_PK IS NULL THEN :NEW.CORREO_ID_CORREO_PK := FIDE_CORREO_SEQ.NEXTVAL; END IF;
        :NEW.CREADO_POR := USER; :NEW.FECHA_CREACION := SYSTIMESTAMP; :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.MODIFICADO_POR := USER; :NEW.FECHA_MODIFICACION := SYSTIMESTAMP; :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_DIRECCIONES_TRG BEFORE INSERT OR UPDATE ON FIDE_DIRECCIONES_TB FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.DIRECCIONES_ID_DIRECCION_PK IS NULL THEN :NEW.DIRECCIONES_ID_DIRECCION_PK := FIDE_DIRECCIONES_SEQ.NEXTVAL; END IF;
        :NEW.CREADO_POR := USER; :NEW.FECHA_CREACION := SYSTIMESTAMP; :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.MODIFICADO_POR := USER; :NEW.FECHA_MODIFICACION := SYSTIMESTAMP; :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_RESERVACIONES_TRG BEFORE INSERT OR UPDATE ON FIDE_RESERVACIONES_TB FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.RESERVACIONES_ID_RESERVACION_PK IS NULL THEN :NEW.RESERVACIONES_ID_RESERVACION_PK := FIDE_RESERVACIONES_SEQ.NEXTVAL; END IF;
        :NEW.CREADO_POR := USER; :NEW.FECHA_CREACION := SYSTIMESTAMP; :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.MODIFICADO_POR := USER; :NEW.FECHA_MODIFICACION := SYSTIMESTAMP; :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_PAQ_SERV_TRG BEFORE INSERT OR UPDATE ON FIDE_PAQUETES_POR_SERVICIO_TB FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER; :NEW.FECHA_CREACION := SYSTIMESTAMP; :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.MODIFICADO_POR := USER; :NEW.FECHA_MODIFICACION := SYSTIMESTAMP; :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_ASIGNACION_TRG BEFORE INSERT OR UPDATE ON FIDE_ASIGNACION_TB FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.ASIGNACION_ID_ASIGNACION_PK IS NULL THEN :NEW.ASIGNACION_ID_ASIGNACION_PK := FIDE_ASIGNACION_SEQ.NEXTVAL; END IF;
        :NEW.CREADO_POR := USER; :NEW.FECHA_CREACION := SYSTIMESTAMP; :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.MODIFICADO_POR := USER; :NEW.FECHA_MODIFICACION := SYSTIMESTAMP; :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_DET_RES_TRG BEFORE INSERT OR UPDATE ON FIDE_DETALLE_RESERVACION_TB FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER; :NEW.FECHA_CREACION := SYSTIMESTAMP; :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.MODIFICADO_POR := USER; :NEW.FECHA_MODIFICACION := SYSTIMESTAMP; :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_FACTURACION_TRG BEFORE INSERT OR UPDATE ON FIDE_FACTURACION_TB FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.FACTURACION_ID_NUMERO_FACTURA_PK IS NULL THEN 
           SELECT FIDE_FACTURACION_SEQ.NEXTVAL INTO :NEW.FACTURACION_ID_NUMERO_FACTURA_PK FROM DUAL;
        END IF;
        :NEW.CREADO_POR := USER;
        :NEW.FECHA_CREACION := SYSTIMESTAMP;
        :NEW.ACCION := 'FOLIO GENERADO: ' || FIDE_SEQUENCIA_ALFANUMERICA_FN(); 
    ELSIF UPDATING THEN
        :NEW.MODIFICADO_POR := USER; :NEW.FECHA_MODIFICACION := SYSTIMESTAMP; :NEW.ACCION := 'UPDATE';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_DET_FACT_TRG BEFORE INSERT OR UPDATE ON FIDE_DETALLE_FACTURA_TB FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.CREADO_POR := USER; :NEW.FECHA_CREACION := SYSTIMESTAMP; :NEW.ACCION := 'INSERT';
    ELSIF UPDATING THEN
        :NEW.MODIFICADO_POR := USER; :NEW.FECHA_MODIFICACION := SYSTIMESTAMP; :NEW.ACCION := 'UPDATE';
    END IF;
END;
/
COMMIT;
