CREATE OR REPLACE PACKAGE FIDE_PROYECTO_FINAL_PKG AS 

    -- --------------------------------------------------------------------------
    -- 1. FIDE_ESTADOS_TB
    -- Nota: Esta tabla se elimina fisicamente ya que no tiene FK de estado.
    -- --------------------------------------------------------------------------
    PROCEDURE FIDE_ESTADOS_INSERTAR_SP (
        P_ESTADOS_ID_ESTADO_PK  IN G2_SC508_VT_PROYECTO.FIDE_ESTADOS_TB.ESTADOS_ID_ESTADO_PK%TYPE,
        P_AMBITO                IN G2_SC508_VT_PROYECTO.FIDE_ESTADOS_TB.ambito%TYPE,
        P_ESTADO                IN G2_SC508_VT_PROYECTO.FIDE_ESTADOS_TB.estado%TYPE
    );

    PROCEDURE FIDE_ESTADOS_ACTUALIZAR_SP (
        P_ESTADOS_ID_ESTADO_PK  IN G2_SC508_VT_PROYECTO.FIDE_ESTADOS_TB.ESTADOS_ID_ESTADO_PK%TYPE,
        P_AMBITO                IN G2_SC508_VT_PROYECTO.FIDE_ESTADOS_TB.ambito%TYPE,
        P_ESTADO                IN G2_SC508_VT_PROYECTO.FIDE_ESTADOS_TB.estado%TYPE
    );

    PROCEDURE FIDE_ESTADOS_ELIMINAR_SP (
        P_ESTADOS_ID_ESTADO_PK  IN G2_SC508_VT_PROYECTO.FIDE_ESTADOS_TB.ESTADOS_ID_ESTADO_PK%TYPE
    );

    -- --------------------------------------------------------------------------
    -- 2. FIDE_ROLES_TB
    -- Nota: Esta tabla se elimina fisicamente ya que no tiene FK de estado.
    -- --------------------------------------------------------------------------
    PROCEDURE FIDE_ROLES_INSERTAR_SP (
        P_ROLES_ID_ROL_PK   IN G2_SC508_VT_PROYECTO.FIDE_ROLES_TB.ROLES_ID_ROL_PK%TYPE,
        P_NOMBRE_ROL        IN G2_SC508_VT_PROYECTO.FIDE_ROLES_TB.nombre_rol%TYPE,
        P_DESCRIPCION       IN G2_SC508_VT_PROYECTO.FIDE_ROLES_TB.descripcion%TYPE
    );

    PROCEDURE FIDE_ROLES_ACTUALIZAR_SP (
        P_ROLES_ID_ROL_PK   IN G2_SC508_VT_PROYECTO.FIDE_ROLES_TB.ROLES_ID_ROL_PK%TYPE,
        P_NOMBRE_ROL        IN G2_SC508_VT_PROYECTO.FIDE_ROLES_TB.nombre_rol%TYPE,
        P_DESCRIPCION       IN G2_SC508_VT_PROYECTO.FIDE_ROLES_TB.descripcion%TYPE
    );

    PROCEDURE FIDE_ROLES_ELIMINAR_SP (
        P_ROLES_ID_ROL_PK   IN G2_SC508_VT_PROYECTO.FIDE_ROLES_TB.ROLES_ID_ROL_PK%TYPE
    );

    -- --------------------------------------------------------------------------
    -- 3. FIDE_PROVINCIA_TB
    -- --------------------------------------------------------------------------
    PROCEDURE FIDE_PROVINCIA_INSERTAR_SP (
        P_PROVINCIA_ID_PROVINCIA_PK IN G2_SC508_VT_PROYECTO.FIDE_PROVINCIA_TB.PROVINCIA_ID_PROVINCIA_PK%TYPE,
        P_NOMBRE                    IN G2_SC508_VT_PROYECTO.FIDE_PROVINCIA_TB.nombre%TYPE
    );

    PROCEDURE FIDE_PROVINCIA_ACTUALIZAR_SP (
        P_PROVINCIA_ID_PROVINCIA_PK IN G2_SC508_VT_PROYECTO.FIDE_PROVINCIA_TB.PROVINCIA_ID_PROVINCIA_PK%TYPE,
        P_NOMBRE                    IN G2_SC508_VT_PROYECTO.FIDE_PROVINCIA_TB.nombre%TYPE,
        P_ESTADOS_ID_ESTADO_FK      IN G2_SC508_VT_PROYECTO.FIDE_PROVINCIA_TB.ESTADOS_ID_ESTADO_FK%TYPE
    );

    PROCEDURE FIDE_PROVINCIA_ELIMINAR_SP (
        P_PROVINCIA_ID_PROVINCIA_PK IN G2_SC508_VT_PROYECTO.FIDE_PROVINCIA_TB.PROVINCIA_ID_PROVINCIA_PK%TYPE,
        P_ID_ESTADO_INACTIVO        IN G2_SC508_VT_PROYECTO.FIDE_ESTADOS_TB.ESTADOS_ID_ESTADO_PK%TYPE DEFAULT 2
    );

    -- --------------------------------------------------------------------------
    -- 4. FIDE_METODO_PAGO_TB
    -- --------------------------------------------------------------------------
    PROCEDURE FIDE_METODO_PAGO_INSERTAR_SP (
        P_METODO_PAGO_ID_METODO_PK  IN G2_SC508_VT_PROYECTO.FIDE_METODO_PAGO_TB.METODO_PAGO_ID_METODO_PK%TYPE,
        P_NOMBRE                    IN G2_SC508_VT_PROYECTO.FIDE_METODO_PAGO_TB.nombre%TYPE
    );

    PROCEDURE FIDE_METODO_PAGO_ACTUALIZAR_SP (
        P_METODO_PAGO_ID_METODO_PK  IN G2_SC508_VT_PROYECTO.FIDE_METODO_PAGO_TB.METODO_PAGO_ID_METODO_PK%TYPE,
        P_NOMBRE                    IN G2_SC508_VT_PROYECTO.FIDE_METODO_PAGO_TB.nombre%TYPE,
        P_ESTADOS_ID_ESTADO_FK      IN G2_SC508_VT_PROYECTO.FIDE_METODO_PAGO_TB.ESTADOS_ID_ESTADO_FK%TYPE
    );

    PROCEDURE FIDE_METODO_PAGO_ELIMINAR_SP (
        P_METODO_PAGO_ID_METODO_PK  IN G2_SC508_VT_PROYECTO.FIDE_METODO_PAGO_TB.METODO_PAGO_ID_METODO_PK%TYPE,
        P_ID_ESTADO_INACTIVO        IN G2_SC508_VT_PROYECTO.FIDE_ESTADOS_TB.ESTADOS_ID_ESTADO_PK%TYPE DEFAULT 2
    );

    -- --------------------------------------------------------------------------
    -- 5. FIDE_CATEGORIA_PRODUCTO_TB
    -- --------------------------------------------------------------------------
    PROCEDURE FIDE_CATEGORIA_PRODUCTO_INSERTAR_SP (
        P_CAT_PROD_ID_CATEGORIA_PK  IN G2_SC508_VT_PROYECTO.FIDE_CATEGORIA_PRODUCTO_TB.CATEGORIA_PRODUCTO_ID_CATEGORIA_PK%TYPE,
        P_NOMBRE                    IN G2_SC508_VT_PROYECTO.FIDE_CATEGORIA_PRODUCTO_TB.nombre%TYPE,
        P_DESCRIPCION               IN G2_SC508_VT_PROYECTO.FIDE_CATEGORIA_PRODUCTO_TB.descripcion%TYPE
    );

    PROCEDURE FIDE_CATEGORIA_PRODUCTO_ACTUALIZAR_SP (
        P_CAT_PROD_ID_CATEGORIA_PK  IN G2_SC508_VT_PROYECTO.FIDE_CATEGORIA_PRODUCTO_TB.CATEGORIA_PRODUCTO_ID_CATEGORIA_PK%TYPE,
        P_NOMBRE                    IN G2_SC508_VT_PROYECTO.FIDE_CATEGORIA_PRODUCTO_TB.nombre%TYPE,
        P_DESCRIPCION               IN G2_SC508_VT_PROYECTO.FIDE_CATEGORIA_PRODUCTO_TB.descripcion%TYPE,
        P_ESTADOS_ID_ESTADO_FK      IN G2_SC508_VT_PROYECTO.FIDE_CATEGORIA_PRODUCTO_TB.ESTADOS_ID_ESTADO_FK%TYPE
    );

    PROCEDURE FIDE_CATEGORIA_PRODUCTO_ELIMINAR_SP (
        P_CAT_PROD_ID_CATEGORIA_PK  IN G2_SC508_VT_PROYECTO.FIDE_CATEGORIA_PRODUCTO_TB.CATEGORIA_PRODUCTO_ID_CATEGORIA_PK%TYPE,
        P_ID_ESTADO_INACTIVO        IN G2_SC508_VT_PROYECTO.FIDE_ESTADOS_TB.ESTADOS_ID_ESTADO_PK%TYPE DEFAULT 2
    );

    -- --------------------------------------------------------------------------
    -- 6. FIDE_CATEGORIA_SERVICIO_TB
    -- --------------------------------------------------------------------------
    PROCEDURE FIDE_CATEGORIA_SERVICIO_INSERTAR_SP (
        P_CAT_SERV_ID_CATEGORIA_PK  IN G2_SC508_VT_PROYECTO.FIDE_CATEGORIA_SERVICIO_TB.CATEGORIA_SERVICIO_ID_CATEGORIA_PK%TYPE,
        P_NOMBRE                    IN G2_SC508_VT_PROYECTO.FIDE_CATEGORIA_SERVICIO_TB.nombre%TYPE,
        P_DESCRIPCION               IN G2_SC508_VT_PROYECTO.FIDE_CATEGORIA_SERVICIO_TB.descripcion%TYPE
    );

    PROCEDURE FIDE_CATEGORIA_SERVICIO_ACTUALIZAR_SP (
        P_CAT_SERV_ID_CATEGORIA_PK  IN G2_SC508_VT_PROYECTO.FIDE_CATEGORIA_SERVICIO_TB.CATEGORIA_SERVICIO_ID_CATEGORIA_PK%TYPE,
        P_NOMBRE                    IN G2_SC508_VT_PROYECTO.FIDE_CATEGORIA_SERVICIO_TB.nombre%TYPE,
        P_DESCRIPCION               IN G2_SC508_VT_PROYECTO.FIDE_CATEGORIA_SERVICIO_TB.descripcion%TYPE,
        P_ESTADOS_ID_ESTADO_FK      IN G2_SC508_VT_PROYECTO.FIDE_CATEGORIA_SERVICIO_TB.ESTADOS_ID_ESTADO_FK%TYPE
    );

    PROCEDURE FIDE_CATEGORIA_SERVICIO_ELIMINAR_SP (
        P_CAT_SERV_ID_CATEGORIA_PK  IN G2_SC508_VT_PROYECTO.FIDE_CATEGORIA_SERVICIO_TB.CATEGORIA_SERVICIO_ID_CATEGORIA_PK%TYPE,
        P_ID_ESTADO_INACTIVO        IN G2_SC508_VT_PROYECTO.FIDE_ESTADOS_TB.ESTADOS_ID_ESTADO_PK%TYPE DEFAULT 2
    );

    -- --------------------------------------------------------------------------
    -- 7. FIDE_PAQUETE_TB
    -- --------------------------------------------------------------------------
    PROCEDURE FIDE_PAQUETE_INSERTAR_SP (
        P_PAQUETE_ID_PAQUETE_PK IN G2_SC508_VT_PROYECTO.FIDE_PAQUETE_TB.PAQUETE_ID_PAQUETE_PK%TYPE,
        P_NOMBRE_PAQUETE        IN G2_SC508_VT_PROYECTO.FIDE_PAQUETE_TB.nombre_paquete%TYPE,
        P_DESCRIPCION           IN G2_SC508_VT_PROYECTO.FIDE_PAQUETE_TB.descripcion%TYPE,
        P_PRECIO_TOTAL          IN G2_SC508_VT_PROYECTO.FIDE_PAQUETE_TB.precio_total%TYPE
    );

    PROCEDURE FIDE_PAQUETE_ACTUALIZAR_SP (
        P_PAQUETE_ID_PAQUETE_PK IN G2_SC508_VT_PROYECTO.FIDE_PAQUETE_TB.PAQUETE_ID_PAQUETE_PK%TYPE,
        P_NOMBRE_PAQUETE        IN G2_SC508_VT_PROYECTO.FIDE_PAQUETE_TB.nombre_paquete%TYPE,
        P_DESCRIPCION           IN G2_SC508_VT_PROYECTO.FIDE_PAQUETE_TB.descripcion%TYPE,
        P_PRECIO_TOTAL          IN G2_SC508_VT_PROYECTO.FIDE_PAQUETE_TB.precio_total%TYPE,
        P_ESTADOS_ID_ESTADO_FK  IN G2_SC508_VT_PROYECTO.FIDE_PAQUETE_TB.ESTADOS_ID_ESTADO_FK%TYPE
    );

    PROCEDURE FIDE_PAQUETE_ELIMINAR_SP (
        P_PAQUETE_ID_PAQUETE_PK IN G2_SC508_VT_PROYECTO.FIDE_PAQUETE_TB.PAQUETE_ID_PAQUETE_PK%TYPE,
        P_ID_ESTADO_INACTIVO    IN G2_SC508_VT_PROYECTO.FIDE_ESTADOS_TB.ESTADOS_ID_ESTADO_PK%TYPE DEFAULT 2
    );

    -- --------------------------------------------------------------------------
    -- 8. FIDE_CANTON_TB
    -- --------------------------------------------------------------------------
    PROCEDURE FIDE_CANTON_INSERTAR_SP (
        P_CANTON_ID_CANTON_PK       IN G2_SC508_VT_PROYECTO.FIDE_CANTON_TB.CANTON_ID_CANTON_PK%TYPE,
        P_PROVINCIA_ID_PROVINCIA_PK IN G2_SC508_VT_PROYECTO.FIDE_CANTON_TB.PROVINCIA_ID_PROVINCIA_PK%TYPE,
        P_NOMBRE                    IN G2_SC508_VT_PROYECTO.FIDE_CANTON_TB.nombre%TYPE
    );

    PROCEDURE FIDE_CANTON_ACTUALIZAR_SP (
        P_CANTON_ID_CANTON_PK       IN G2_SC508_VT_PROYECTO.FIDE_CANTON_TB.CANTON_ID_CANTON_PK%TYPE,
        P_PROVINCIA_ID_PROVINCIA_PK IN G2_SC508_VT_PROYECTO.FIDE_CANTON_TB.PROVINCIA_ID_PROVINCIA_PK%TYPE,
        P_NOMBRE                    IN G2_SC508_VT_PROYECTO.FIDE_CANTON_TB.nombre%TYPE,
        P_ESTADOS_ID_ESTADO_FK      IN G2_SC508_VT_PROYECTO.FIDE_CANTON_TB.ESTADOS_ID_ESTADO_FK%TYPE
    );

    PROCEDURE FIDE_CANTON_ELIMINAR_SP (
        P_CANTON_ID_CANTON_PK   IN G2_SC508_VT_PROYECTO.FIDE_CANTON_TB.CANTON_ID_CANTON_PK%TYPE,
        P_ID_ESTADO_INACTIVO    IN G2_SC508_VT_PROYECTO.FIDE_ESTADOS_TB.ESTADOS_ID_ESTADO_PK%TYPE DEFAULT 2
    );

    -- --------------------------------------------------------------------------
    -- 9. FIDE_DISTRITO_TB
    -- --------------------------------------------------------------------------
    PROCEDURE FIDE_DISTRITO_INSERTAR_SP (
        P_DISTRITO_ID_DISTRITO_PK   IN G2_SC508_VT_PROYECTO.FIDE_DISTRITO_TB.DISTRITO_ID_DISTRITO_PK%TYPE,
        P_CANTON_ID_CANTON_PK       IN G2_SC508_VT_PROYECTO.FIDE_DISTRITO_TB.CANTON_ID_CANTON_PK%TYPE,
        P_NOMBRE                    IN G2_SC508_VT_PROYECTO.FIDE_DISTRITO_TB.nombre%TYPE
    );

    PROCEDURE FIDE_DISTRITO_ACTUALIZAR_SP (
        P_DISTRITO_ID_DISTRITO_PK   IN G2_SC508_VT_PROYECTO.FIDE_DISTRITO_TB.DISTRITO_ID_DISTRITO_PK%TYPE,
        P_CANTON_ID_CANTON_PK       IN G2_SC508_VT_PROYECTO.FIDE_DISTRITO_TB.CANTON_ID_CANTON_PK%TYPE,
        P_NOMBRE                    IN G2_SC508_VT_PROYECTO.FIDE_DISTRITO_TB.nombre%TYPE,
        P_ESTADOS_ID_ESTADO_FK      IN G2_SC508_VT_PROYECTO.FIDE_DISTRITO_TB.ESTADOS_ID_ESTADO_FK%TYPE
    );

    PROCEDURE FIDE_DISTRITO_ELIMINAR_SP (
        P_DISTRITO_ID_DISTRITO_PK   IN G2_SC508_VT_PROYECTO.FIDE_DISTRITO_TB.DISTRITO_ID_DISTRITO_PK%TYPE,
        P_ID_ESTADO_INACTIVO        IN G2_SC508_VT_PROYECTO.FIDE_ESTADOS_TB.ESTADOS_ID_ESTADO_PK%TYPE DEFAULT 2
    );

    -- --------------------------------------------------------------------------
    -- 10. FIDE_USUARIOS_TB
    -- --------------------------------------------------------------------------
    PROCEDURE FIDE_USUARIOS_INSERTAR_SP (
        P_USUARIOS_ID_CEDULA_PK IN G2_SC508_VT_PROYECTO.FIDE_USUARIOS_TB.USUARIOS_ID_CEDULA_PK%TYPE,
        P_NOMBRE                IN G2_SC508_VT_PROYECTO.FIDE_USUARIOS_TB.nombre%TYPE,
        P_PRIMER_APELLIDO       IN G2_SC508_VT_PROYECTO.FIDE_USUARIOS_TB.primer_apellido%TYPE,
        P_SEGUNDO_APELLIDO      IN G2_SC508_VT_PROYECTO.FIDE_USUARIOS_TB.segundo_apellido%TYPE,
        P_CONTRASENA            IN G2_SC508_VT_PROYECTO.FIDE_USUARIOS_TB.contrasena%TYPE,
        P_ROLES_ID_ROL_PK       IN G2_SC508_VT_PROYECTO.FIDE_USUARIOS_TB.ROLES_ID_ROL_PK%TYPE
    );

    PROCEDURE FIDE_USUARIOS_ACTUALIZAR_SP (
        P_USUARIOS_ID_CEDULA_PK IN G2_SC508_VT_PROYECTO.FIDE_USUARIOS_TB.USUARIOS_ID_CEDULA_PK%TYPE,
        P_NOMBRE                IN G2_SC508_VT_PROYECTO.FIDE_USUARIOS_TB.nombre%TYPE,
        P_PRIMER_APELLIDO       IN G2_SC508_VT_PROYECTO.FIDE_USUARIOS_TB.primer_apellido%TYPE,
        P_SEGUNDO_APELLIDO      IN G2_SC508_VT_PROYECTO.FIDE_USUARIOS_TB.segundo_apellido%TYPE,
        P_CONTRASENA            IN G2_SC508_VT_PROYECTO.FIDE_USUARIOS_TB.contrasena%TYPE,
        P_ESTADOS_ID_ESTADO_PK  IN G2_SC508_VT_PROYECTO.FIDE_USUARIOS_TB.ESTADOS_ID_ESTADO_PK%TYPE,
        P_ROLES_ID_ROL_PK       IN G2_SC508_VT_PROYECTO.FIDE_USUARIOS_TB.ROLES_ID_ROL_PK%TYPE
    );

    PROCEDURE FIDE_USUARIOS_ELIMINAR_SP (
        P_USUARIOS_ID_CEDULA_PK IN G2_SC508_VT_PROYECTO.FIDE_USUARIOS_TB.USUARIOS_ID_CEDULA_PK%TYPE,
        P_ID_ESTADO_INACTIVO    IN G2_SC508_VT_PROYECTO.FIDE_ESTADOS_TB.ESTADOS_ID_ESTADO_PK%TYPE DEFAULT 2
    );

    -- --------------------------------------------------------------------------
    -- 11. FIDE_PRODUCTOS_TB
    -- --------------------------------------------------------------------------
    PROCEDURE FIDE_PRODUCTOS_INSERTAR_SP (
        P_PRODUCTO_ID_PRODUCTO_PK           IN G2_SC508_VT_PROYECTO.FIDE_PRODUCTOS_TB.PRODUCTO_ID_PRODUCTO_PK%TYPE,
        P_NOMBRE                            IN G2_SC508_VT_PROYECTO.FIDE_PRODUCTOS_TB.nombre%TYPE,
        P_DESCRIPCION                       IN G2_SC508_VT_PROYECTO.FIDE_PRODUCTOS_TB.descripcion%TYPE,
        P_PRECIO_UNITARIO                   IN G2_SC508_VT_PROYECTO.FIDE_PRODUCTOS_TB.precio_unitario%TYPE,
        P_CANTIDAD                          IN G2_SC508_VT_PROYECTO.FIDE_PRODUCTOS_TB.cantidad%TYPE,
        P_CATEGORIA_PRODUCTO_ID_CATEGORIA_PK IN G2_SC508_VT_PROYECTO.FIDE_PRODUCTOS_TB.CATEGORIA_PRODUCTO_ID_CATEGORIA_PK%TYPE
    );

    PROCEDURE FIDE_PRODUCTOS_ACTUALIZAR_SP (
        P_PRODUCTO_ID_PRODUCTO_PK           IN G2_SC508_VT_PROYECTO.FIDE_PRODUCTOS_TB.PRODUCTO_ID_PRODUCTO_PK%TYPE,
        P_NOMBRE                            IN G2_SC508_VT_PROYECTO.FIDE_PRODUCTOS_TB.nombre%TYPE,
        P_DESCRIPCION                       IN G2_SC508_VT_PROYECTO.FIDE_PRODUCTOS_TB.descripcion%TYPE,
        P_PRECIO_UNITARIO                   IN G2_SC508_VT_PROYECTO.FIDE_PRODUCTOS_TB.precio_unitario%TYPE,
        P_CANTIDAD                          IN G2_SC508_VT_PROYECTO.FIDE_PRODUCTOS_TB.cantidad%TYPE,
        P_CATEGORIA_PRODUCTO_ID_CATEGORIA_PK IN G2_SC508_VT_PROYECTO.FIDE_PRODUCTOS_TB.CATEGORIA_PRODUCTO_ID_CATEGORIA_PK%TYPE,
        P_ESTADOS_ID_ESTADO_PK              IN G2_SC508_VT_PROYECTO.FIDE_PRODUCTOS_TB.ESTADOS_ID_ESTADO_PK%TYPE
    );

    PROCEDURE FIDE_PRODUCTOS_ELIMINAR_SP (
        P_PRODUCTO_ID_PRODUCTO_PK   IN G2_SC508_VT_PROYECTO.FIDE_PRODUCTOS_TB.PRODUCTO_ID_PRODUCTO_PK%TYPE,
        P_ID_ESTADO_INACTIVO        IN G2_SC508_VT_PROYECTO.FIDE_ESTADOS_TB.ESTADOS_ID_ESTADO_PK%TYPE DEFAULT 2
    );

    -- --------------------------------------------------------------------------
    -- 12. FIDE_SERVICIOS_TB
    -- --------------------------------------------------------------------------
    PROCEDURE FIDE_SERVICIOS_INSERTAR_SP (
        P_SERVICIOS_ID_SERVICIO_PK          IN G2_SC508_VT_PROYECTO.FIDE_SERVICIOS_TB.SERVICIOS_ID_SERVICIO_PK%TYPE,
        P_NOMBRE                            IN G2_SC508_VT_PROYECTO.FIDE_SERVICIOS_TB.nombre%TYPE,
        P_DESCRIPCION                       IN G2_SC508_VT_PROYECTO.FIDE_SERVICIOS_TB.descripcion%TYPE,
        P_PRECIO                            IN G2_SC508_VT_PROYECTO.FIDE_SERVICIOS_TB.precio%TYPE,
        P_CATEGORIA_SERVICIO_ID_CATEGORIA_PK IN G2_SC508_VT_PROYECTO.FIDE_SERVICIOS_TB.CATEGORIA_SERVICIO_ID_CATEGORIA_PK%TYPE
    );

    PROCEDURE FIDE_SERVICIOS_ACTUALIZAR_SP (
        P_SERVICIOS_ID_SERVICIO_PK          IN G2_SC508_VT_PROYECTO.FIDE_SERVICIOS_TB.SERVICIOS_ID_SERVICIO_PK%TYPE,
        P_NOMBRE                            IN G2_SC508_VT_PROYECTO.FIDE_SERVICIOS_TB.nombre%TYPE,
        P_DESCRIPCION                       IN G2_SC508_VT_PROYECTO.FIDE_SERVICIOS_TB.descripcion%TYPE,
        P_PRECIO                            IN G2_SC508_VT_PROYECTO.FIDE_SERVICIOS_TB.precio%TYPE,
        P_CATEGORIA_SERVICIO_ID_CATEGORIA_PK IN G2_SC508_VT_PROYECTO.FIDE_SERVICIOS_TB.CATEGORIA_SERVICIO_ID_CATEGORIA_PK%TYPE,
        P_ESTADOS_ID_ESTADO_PK              IN G2_SC508_VT_PROYECTO.FIDE_SERVICIOS_TB.ESTADOS_ID_ESTADO_PK%TYPE
    );

    PROCEDURE FIDE_SERVICIOS_ELIMINAR_SP (
        P_SERVICIOS_ID_SERVICIO_PK  IN G2_SC508_VT_PROYECTO.FIDE_SERVICIOS_TB.SERVICIOS_ID_SERVICIO_PK%TYPE,
        P_ID_ESTADO_INACTIVO        IN G2_SC508_VT_PROYECTO.FIDE_ESTADOS_TB.ESTADOS_ID_ESTADO_PK%TYPE DEFAULT 2
    );


    -- --------------------------------------------------------------------------
    -- 13. FIDE_PAGOS_TB
    -- --------------------------------------------------------------------------
    PROCEDURE FIDE_PAGOS_INSERTAR_SP (
        P_PAGOS_ID_PAGO_PK          IN G2_SC508_VT_PROYECTO.FIDE_PAGOS_TB.PAGOS_ID_PAGO_PK%TYPE,
        P_FECHA_PAGO                IN G2_SC508_VT_PROYECTO.FIDE_PAGOS_TB.fecha_pago%TYPE,
        P_MONTO                     IN G2_SC508_VT_PROYECTO.FIDE_PAGOS_TB.monto%TYPE,
        P_METODO_PAGO_ID_METODO_PK  IN G2_SC508_VT_PROYECTO.FIDE_PAGOS_TB.METODO_PAGO_ID_METODO_PK%TYPE
    );

    PROCEDURE FIDE_PAGOS_ACTUALIZAR_SP (
        P_PAGOS_ID_PAGO_PK          IN G2_SC508_VT_PROYECTO.FIDE_PAGOS_TB.PAGOS_ID_PAGO_PK%TYPE,
        P_FECHA_PAGO                IN G2_SC508_VT_PROYECTO.FIDE_PAGOS_TB.fecha_pago%TYPE,
        P_MONTO                     IN G2_SC508_VT_PROYECTO.FIDE_PAGOS_TB.monto%TYPE,
        P_METODO_PAGO_ID_METODO_PK  IN G2_SC508_VT_PROYECTO.FIDE_PAGOS_TB.METODO_PAGO_ID_METODO_PK%TYPE,
        P_ESTADOS_ID_ESTADO_PK      IN G2_SC508_VT_PROYECTO.FIDE_PAGOS_TB.ESTADOS_ID_ESTADO_PK%TYPE
    );

    PROCEDURE FIDE_PAGOS_ELIMINAR_SP (
        P_PAGOS_ID_PAGO_PK      IN G2_SC508_VT_PROYECTO.FIDE_PAGOS_TB.PAGOS_ID_PAGO_PK%TYPE,
        P_ID_ESTADO_INACTIVO    IN G2_SC508_VT_PROYECTO.FIDE_ESTADOS_TB.ESTADOS_ID_ESTADO_PK%TYPE DEFAULT 2
    );

    -- --------------------------------------------------------------------------
    -- 14. FIDE_CLIENTES_TB
    -- --------------------------------------------------------------------------
    PROCEDURE FIDE_CLIENTES_INSERTAR_SP (
        P_USUARIOS_ID_CEDULA_PK IN G2_SC508_VT_PROYECTO.FIDE_CLIENTES_TB.USUARIOS_ID_CEDULA_PK%TYPE,
        P_TELEFONO              IN G2_SC508_VT_PROYECTO.FIDE_CLIENTES_TB.telefono%TYPE
    );

    PROCEDURE FIDE_CLIENTES_ACTUALIZAR_SP (
        P_USUARIOS_ID_CEDULA_PK IN G2_SC508_VT_PROYECTO.FIDE_CLIENTES_TB.USUARIOS_ID_CEDULA_PK%TYPE,
        P_TELEFONO              IN G2_SC508_VT_PROYECTO.FIDE_CLIENTES_TB.telefono%TYPE
    );

    PROCEDURE FIDE_CLIENTES_ELIMINAR_SP (
        P_USUARIOS_ID_CEDULA_PK IN G2_SC508_VT_PROYECTO.FIDE_CLIENTES_TB.USUARIOS_ID_CEDULA_PK%TYPE,
        P_ID_ESTADO_INACTIVO    IN G2_SC508_VT_PROYECTO.FIDE_ESTADOS_TB.ESTADOS_ID_ESTADO_PK%TYPE DEFAULT 2
    );

    -- --------------------------------------------------------------------------
    -- 15. FIDE_EMPLEADOS_TB
    -- --------------------------------------------------------------------------
    PROCEDURE FIDE_EMPLEADOS_INSERTAR_SP (
        P_USUARIOS_ID_CEDULA_PK IN G2_SC508_VT_PROYECTO.FIDE_EMPLEADOS_TB.USUARIOS_ID_CEDULA_PK%TYPE,
        P_PUESTO                IN G2_SC508_VT_PROYECTO.FIDE_EMPLEADOS_TB.puesto%TYPE,
        P_FECHA_CONTRATACION    IN G2_SC508_VT_PROYECTO.FIDE_EMPLEADOS_TB.fecha_contratacion%TYPE
    );

    PROCEDURE FIDE_EMPLEADOS_ACTUALIZAR_SP (
        P_USUARIOS_ID_CEDULA_PK IN G2_SC508_VT_PROYECTO.FIDE_EMPLEADOS_TB.USUARIOS_ID_CEDULA_PK%TYPE,
        P_PUESTO                IN G2_SC508_VT_PROYECTO.FIDE_EMPLEADOS_TB.puesto%TYPE,
        P_FECHA_CONTRATACION    IN G2_SC508_VT_PROYECTO.FIDE_EMPLEADOS_TB.fecha_contratacion%TYPE
    );

    PROCEDURE FIDE_EMPLEADOS_ELIMINAR_SP (
        P_USUARIOS_ID_CEDULA_PK IN G2_SC508_VT_PROYECTO.FIDE_EMPLEADOS_TB.USUARIOS_ID_CEDULA_PK%TYPE,
        P_ID_ESTADO_INACTIVO    IN G2_SC508_VT_PROYECTO.FIDE_ESTADOS_TB.ESTADOS_ID_ESTADO_PK%TYPE DEFAULT 2
    );


    -- --------------------------------------------------------------------------
    -- 16. FIDE_CORREO_TB
    -- --------------------------------------------------------------------------
    PROCEDURE FIDE_CORREO_INSERTAR_SP (
        P_CORREO_ID_CORREO_PK   IN G2_SC508_VT_PROYECTO.FIDE_CORREO_TB.CORREO_ID_CORREO_PK%TYPE,
        P_CORREO_ELECTRONICO    IN G2_SC508_VT_PROYECTO.FIDE_CORREO_TB.correo_electronico%TYPE,
        P_TIPO_CORREO           IN G2_SC508_VT_PROYECTO.FIDE_CORREO_TB.tipo_correo%TYPE,
        P_USUARIOS_ID_CEDULA_PK IN G2_SC508_VT_PROYECTO.FIDE_CORREO_TB.USUARIOS_ID_CEDULA_PK%TYPE
    );

    PROCEDURE FIDE_CORREO_ACTUALIZAR_SP (
        P_CORREO_ID_CORREO_PK   IN G2_SC508_VT_PROYECTO.FIDE_CORREO_TB.CORREO_ID_CORREO_PK%TYPE,
        P_CORREO_ELECTRONICO    IN G2_SC508_VT_PROYECTO.FIDE_CORREO_TB.correo_electronico%TYPE,
        P_TIPO_CORREO           IN G2_SC508_VT_PROYECTO.FIDE_CORREO_TB.tipo_correo%TYPE,
        P_ESTADOS_ID_ESTADO_FK  IN G2_SC508_VT_PROYECTO.FIDE_CORREO_TB.ESTADOS_ID_ESTADO_FK%TYPE
    );

    PROCEDURE FIDE_CORREO_ELIMINAR_SP (
        P_CORREO_ID_CORREO_PK   IN G2_SC508_VT_PROYECTO.FIDE_CORREO_TB.CORREO_ID_CORREO_PK%TYPE,
        P_ID_ESTADO_INACTIVO    IN G2_SC508_VT_PROYECTO.FIDE_ESTADOS_TB.ESTADOS_ID_ESTADO_PK%TYPE DEFAULT 2
    );


    -- --------------------------------------------------------------------------
    -- 17. FIDE_DIRECCIONES_TB
    -- --------------------------------------------------------------------------
    PROCEDURE FIDE_DIRECCIONES_INSERTAR_SP (
        P_DIRECCIONES_ID_DIRECCION_PK   IN G2_SC508_VT_PROYECTO.FIDE_DIRECCIONES_TB.DIRECCIONES_ID_DIRECCION_PK%TYPE,
        P_DISTRITO_ID_DISTRITO_PK       IN G2_SC508_VT_PROYECTO.FIDE_DIRECCIONES_TB.DISTRITO_ID_DISTRITO_PK%TYPE,
        P_USUARIOS_ID_CEDULA_PK         IN G2_SC508_VT_PROYECTO.FIDE_DIRECCIONES_TB.USUARIOS_ID_CEDULA_PK%TYPE,
        P_DESCRIPCION                   IN G2_SC508_VT_PROYECTO.FIDE_DIRECCIONES_TB.descripcion%TYPE
    );

    PROCEDURE FIDE_DIRECCIONES_ACTUALIZAR_SP (
        P_DIRECCIONES_ID_DIRECCION_PK   IN G2_SC508_VT_PROYECTO.FIDE_DIRECCIONES_TB.DIRECCIONES_ID_DIRECCION_PK%TYPE,
        P_DISTRITO_ID_DISTRITO_PK       IN G2_SC508_VT_PROYECTO.FIDE_DIRECCIONES_TB.DISTRITO_ID_DISTRITO_PK%TYPE,
        P_DESCRIPCION                   IN G2_SC508_VT_PROYECTO.FIDE_DIRECCIONES_TB.descripcion%TYPE,
        P_ESTADOS_ID_ESTADO_PK          IN G2_SC508_VT_PROYECTO.FIDE_DIRECCIONES_TB.ESTADOS_ID_ESTADO_PK%TYPE
    );

    PROCEDURE FIDE_DIRECCIONES_ELIMINAR_SP (
        P_DIRECCIONES_ID_DIRECCION_PK   IN G2_SC508_VT_PROYECTO.FIDE_DIRECCIONES_TB.DIRECCIONES_ID_DIRECCION_PK%TYPE,
        P_ID_ESTADO_INACTIVO            IN G2_SC508_VT_PROYECTO.FIDE_ESTADOS_TB.ESTADOS_ID_ESTADO_PK%TYPE DEFAULT 2
    );


    -- --------------------------------------------------------------------------
    -- 18. FIDE_RESERVACIONES_TB
    -- --------------------------------------------------------------------------
    PROCEDURE FIDE_RESERVACIONES_INSERTAR_SP (
        P_RESERVACIONES_ID_RESERVACION_PK IN G2_SC508_VT_PROYECTO.FIDE_RESERVACIONES_TB.RESERVACIONES_ID_RESERVACION_PK%TYPE,
        P_FECHA_RESERVACION               IN G2_SC508_VT_PROYECTO.FIDE_RESERVACIONES_TB.fecha_reservacion%TYPE,
        P_HORA_INICIO                     IN G2_SC508_VT_PROYECTO.FIDE_RESERVACIONES_TB.hora_inicio%TYPE,
        P_HORA_FIN                        IN G2_SC508_VT_PROYECTO.FIDE_RESERVACIONES_TB.hora_fin%TYPE,
        P_USUARIOS_ID_CEDULA_PK           IN G2_SC508_VT_PROYECTO.FIDE_RESERVACIONES_TB.USUARIOS_ID_CEDULA_PK%TYPE,
        P_DIRECCIONES_ID_DIRECCION_PK     IN G2_SC508_VT_PROYECTO.FIDE_RESERVACIONES_TB.DIRECCIONES_ID_DIRECCION_PK%TYPE
    );

    PROCEDURE FIDE_RESERVACIONES_ACTUALIZAR_SP (
        P_RESERVACIONES_ID_RESERVACION_PK IN G2_SC508_VT_PROYECTO.FIDE_RESERVACIONES_TB.RESERVACIONES_ID_RESERVACION_PK%TYPE,
        P_FECHA_RESERVACION               IN G2_SC508_VT_PROYECTO.FIDE_RESERVACIONES_TB.fecha_reservacion%TYPE,
        P_HORA_INICIO                     IN G2_SC508_VT_PROYECTO.FIDE_RESERVACIONES_TB.hora_inicio%TYPE,
        P_HORA_FIN                        IN G2_SC508_VT_PROYECTO.FIDE_RESERVACIONES_TB.hora_fin%TYPE,
        P_ESTADOS_ID_ESTADO_PK            IN G2_SC508_VT_PROYECTO.FIDE_RESERVACIONES_TB.ESTADOS_ID_ESTADO_PK%TYPE,
        P_USUARIOS_ID_CEDULA_PK           IN G2_SC508_VT_PROYECTO.FIDE_RESERVACIONES_TB.USUARIOS_ID_CEDULA_PK%TYPE,
        P_DIRECCIONES_ID_DIRECCION_PK     IN G2_SC508_VT_PROYECTO.FIDE_RESERVACIONES_TB.DIRECCIONES_ID_DIRECCION_PK%TYPE
    );

    PROCEDURE FIDE_RESERVACIONES_ELIMINAR_SP (
        P_RESERVACIONES_ID_RESERVACION_PK IN G2_SC508_VT_PROYECTO.FIDE_RESERVACIONES_TB.RESERVACIONES_ID_RESERVACION_PK%TYPE,
        P_ID_ESTADO_CANCELADO             IN G2_SC508_VT_PROYECTO.FIDE_ESTADOS_TB.ESTADOS_ID_ESTADO_PK%TYPE DEFAULT 5 -- Asumiendo 5 como "Cancelado"
    );


    -- --------------------------------------------------------------------------
    -- 19. FIDE_PAQUETES_POR_SERVICIO_TB (Tabla Intermedia sin estado propio)
    -- Se maneja como PK compuesta.
    -- --------------------------------------------------------------------------
    PROCEDURE FIDE_PAQUETES_POR_SERVICIO_INSERTAR_SP (
        P_PAQUETE_ID_PAQUETE_PK IN G2_SC508_VT_PROYECTO.FIDE_PAQUETES_POR_SERVICIO_TB.PAQUETE_ID_PAQUETE_PK%TYPE,
        P_SERVICIOS_ID_SERVICIO_PK IN G2_SC508_VT_PROYECTO.FIDE_PAQUETES_POR_SERVICIO_TB.SERVICIOS_ID_SERVICIO_PK%TYPE
    );

    -- Nota: No se requiere actualizar PKs/FKs. Si se necesitan cambiar, es mejor eliminar e insertar.

    PROCEDURE FIDE_PAQUETES_POR_SERVICIO_ELIMINAR_SP (
        P_PAQUETE_ID_PAQUETE_PK IN G2_SC508_VT_PROYECTO.FIDE_PAQUETES_POR_SERVICIO_TB.PAQUETE_ID_PAQUETE_PK%TYPE,
        P_SERVICIOS_ID_SERVICIO_PK IN G2_SC508_VT_PROYECTO.FIDE_PAQUETES_POR_SERVICIO_TB.SERVICIOS_ID_SERVICIO_PK%TYPE
    );


    -- --------------------------------------------------------------------------
    -- 20. FIDE_ASIGNACION_TB
    -- --------------------------------------------------------------------------
    PROCEDURE FIDE_ASIGNACION_INSERTAR_SP (
        P_ASIGNACION_ID_ASIGNACION_PK IN G2_SC508_VT_PROYECTO.FIDE_ASIGNACION_TB.ASIGNACION_ID_ASIGNACION_PK%TYPE,
        P_NOTAS                       IN G2_SC508_VT_PROYECTO.FIDE_ASIGNACION_TB.Notas%TYPE,
        P_PRODUCTO_ID_PRODUCTO_PK     IN G2_SC508_VT_PROYECTO.FIDE_ASIGNACION_TB.PRODUCTO_ID_PRODUCTO_PK%TYPE,
        P_RESERVACIONES_ID_RESERVACION_PK IN G2_SC508_VT_PROYECTO.FIDE_ASIGNACION_TB.RESERVACIONES_ID_RESERVACION_PK%TYPE
    );

    PROCEDURE FIDE_ASIGNACION_ACTUALIZAR_SP (
        P_ASIGNACION_ID_ASIGNACION_PK IN G2_SC508_VT_PROYECTO.FIDE_ASIGNACION_TB.ASIGNACION_ID_ASIGNACION_PK%TYPE,
        P_NOTAS                       IN G2_SC508_VT_PROYECTO.FIDE_ASIGNACION_TB.Notas%TYPE,
        P_PRODUCTO_ID_PRODUCTO_PK     IN G2_SC508_VT_PROYECTO.FIDE_ASIGNACION_TB.PRODUCTO_ID_PRODUCTO_PK%TYPE,
        P_RESERVACIONES_ID_RESERVACION_PK IN G2_SC508_VT_PROYECTO.FIDE_ASIGNACION_TB.RESERVACIONES_ID_RESERVACION_PK%TYPE
    );

    PROCEDURE FIDE_ASIGNACION_ELIMINAR_SP (
        P_ASIGNACION_ID_ASIGNACION_PK IN G2_SC508_VT_PROYECTO.FIDE_ASIGNACION_TB.ASIGNACION_ID_ASIGNACION_PK%TYPE
    );


    -- --------------------------------------------------------------------------
    -- 21. FIDE_DETALLE_RESERVACION_TB
    -- --------------------------------------------------------------------------
    PROCEDURE FIDE_DETALLE_RESERVACION_INSERTAR_SP (
        P_RESERVACIONES_ID_RESERVACION_PK IN G2_SC508_VT_PROYECTO.FIDE_DETALLE_RESERVACION_TB.RESERVACIONES_ID_RESERVACION_PK%TYPE,
        P_NUMERO_LINEA              IN G2_SC508_VT_PROYECTO.FIDE_DETALLE_RESERVACION_TB.NUMERO_LINEA%TYPE,
        P_CANTIDAD                  IN G2_SC508_VT_PROYECTO.FIDE_DETALLE_RESERVACION_TB.cantidad%TYPE,
        P_PRECIO_UNITARIO           IN G2_SC508_VT_PROYECTO.FIDE_DETALLE_RESERVACION_TB.precio_unitario%TYPE,
        P_SERVICIOS_ID_SERVICIO_PK  IN G2_SC508_VT_PROYECTO.FIDE_DETALLE_RESERVACION_TB.SERVICIOS_ID_SERVICIO_PK%TYPE,
        P_PAQUETE_ID_PAQUETE_PK     IN G2_SC508_VT_PROYECTO.FIDE_DETALLE_RESERVACION_TB.PAQUETE_ID_PAQUETE_PK%TYPE
    );

    PROCEDURE FIDE_DETALLE_RESERVACION_ACTUALIZAR_SP (
        P_RESERVACIONES_ID_RESERVACION_PK IN G2_SC508_VT_PROYECTO.FIDE_DETALLE_RESERVACION_TB.RESERVACIONES_ID_RESERVACION_PK%TYPE,
        P_NUMERO_LINEA              IN G2_SC508_VT_PROYECTO.FIDE_DETALLE_RESERVACION_TB.NUMERO_LINEA%TYPE,
        P_CANTIDAD                  IN G2_SC508_VT_PROYECTO.FIDE_DETALLE_RESERVACION_TB.cantidad%TYPE,
        P_PRECIO_UNITARIO           IN G2_SC508_VT_PROYECTO.FIDE_DETALLE_RESERVACION_TB.precio_unitario%TYPE,
        P_SERVICIOS_ID_SERVICIO_PK  IN G2_SC508_VT_PROYECTO.FIDE_DETALLE_RESERVACION_TB.SERVICIOS_ID_SERVICIO_PK%TYPE,
        P_PAQUETE_ID_PAQUETE_PK     IN G2_SC508_VT_PROYECTO.FIDE_DETALLE_RESERVACION_TB.PAQUETE_ID_PAQUETE_PK%TYPE
    );

    PROCEDURE FIDE_DETALLE_RESERVACION_ELIMINAR_SP (
        P_RESERVACIONES_ID_RESERVACION_PK IN G2_SC508_VT_PROYECTO.FIDE_DETALLE_RESERVACION_TB.RESERVACIONES_ID_RESERVACION_PK%TYPE,
        P_NUMERO_LINEA              IN G2_SC508_VT_PROYECTO.FIDE_DETALLE_RESERVACION_TB.NUMERO_LINEA%TYPE
    );


    -- --------------------------------------------------------------------------
    -- 22. FIDE_FACTURACION_TB
    -- --------------------------------------------------------------------------
    PROCEDURE FIDE_FACTURACION_INSERTAR_SP (
        P_FACT_ID_NUMERO_FACTURA_PK IN G2_SC508_VT_PROYECTO.FIDE_FACTURACION_TB.FACTURACION_ID_NUMERO_FACTURA_PK%TYPE,
        P_FECHA_EMISION             IN G2_SC508_VT_PROYECTO.FIDE_FACTURACION_TB.fecha_emision%TYPE,
        P_MONTO_TOTAL               IN G2_SC508_VT_PROYECTO.FIDE_FACTURACION_TB.monto_total%TYPE,
        P_IMPUESTOS                 IN G2_SC508_VT_PROYECTO.FIDE_FACTURACION_TB.impuestos%TYPE,
        P_DETALLE_FACTURA           IN G2_SC508_VT_PROYECTO.FIDE_FACTURACION_TB.destalle_factura%TYPE,
        P_PAGOS_ID_PAGO_PK          IN G2_SC508_VT_PROYECTO.FIDE_FACTURACION_TB.PAGOS_ID_PAGO_PK%TYPE,
        P_RESERVACIONES_ID_RES_PK   IN G2_SC508_VT_PROYECTO.FIDE_FACTURACION_TB.RESERVACIONES_ID_RESERVACION_PK%TYPE
    );

    PROCEDURE FIDE_FACTURACION_ACTUALIZAR_SP (
        P_FACT_ID_NUMERO_FACTURA_PK IN G2_SC508_VT_PROYECTO.FIDE_FACTURACION_TB.FACTURACION_ID_NUMERO_FACTURA_PK%TYPE,
        P_FECHA_EMISION             IN G2_SC508_VT_PROYECTO.FIDE_FACTURACION_TB.fecha_emision%TYPE,
        P_MONTO_TOTAL               IN G2_SC508_VT_PROYECTO.FIDE_FACTURACION_TB.monto_total%TYPE,
        P_IMPUESTOS                 IN G2_SC508_VT_PROYECTO.FIDE_FACTURACION_TB.impuestos%TYPE,
        P_DETALLE_FACTURA           IN G2_SC508_VT_PROYECTO.FIDE_FACTURACION_TB.destalle_factura%TYPE,
        P_PAGOS_ID_PAGO_PK          IN G2_SC508_VT_PROYECTO.FIDE_FACTURACION_TB.PAGOS_ID_PAGO_PK%TYPE,
        P_ESTADOS_ID_ESTADO_PK      IN G2_SC508_VT_PROYECTO.FIDE_FACTURACION_TB.ESTADOS_ID_ESTADO_PK%TYPE,
        P_RESERVACIONES_ID_RES_PK   IN G2_SC508_VT_PROYECTO.FIDE_FACTURACION_TB.RESERVACIONES_ID_RESERVACION_PK%TYPE
    );

    PROCEDURE FIDE_FACTURACION_ELIMINAR_SP (
        P_FACT_ID_NUMERO_FACTURA_PK IN G2_SC508_VT_PROYECTO.FIDE_FACTURACION_TB.FACTURACION_ID_NUMERO_FACTURA_PK%TYPE,
        P_ID_ESTADO_ANULADO         IN G2_SC508_VT_PROYECTO.FIDE_ESTADOS_TB.ESTADOS_ID_ESTADO_PK%TYPE DEFAULT 2
    );

    -- --------------------------------------------------------------------------
    -- 23. FIDE_DETALLE_FACTURA_TB CRUD (Borrado Físico)
    -- --------------------------------------------------------------------------
    PROCEDURE FIDE_DETALLE_FACTURA_INSERTAR_SP (
        P_FACTURACION_ID_NUMERO_FACTURA_FK IN G2_SC508_VT_PROYECTO.FIDE_DETALLE_FACTURA_TB.FACTURACION_ID_NUMERO_FACTURA_FK%TYPE,
        P_NUMERO_LINEA                     IN G2_SC508_VT_PROYECTO.FIDE_DETALLE_FACTURA_TB.NUMERO_LINEA%TYPE,
        P_CANTIDAD                         IN G2_SC508_VT_PROYECTO.FIDE_DETALLE_FACTURA_TB.cantidad%TYPE,
        P_PRECIO_UNITARIO                  IN G2_SC508_VT_PROYECTO.FIDE_DETALLE_FACTURA_TB.precio_unitario%TYPE,
        P_SUBTOTAL_LINEA                   IN G2_SC508_VT_PROYECTO.FIDE_DETALLE_FACTURA_TB.subtotal_linea%TYPE,
        P_SERVICIOS_ID_SERVICIO_PK         IN G2_SC508_VT_PROYECTO.FIDE_DETALLE_FACTURA_TB.SERVICIOS_ID_SERVICIO_PK%TYPE
    );

    PROCEDURE FIDE_DETALLE_FACTURA_ACTUALIZAR_SP (
        P_FACTURACION_ID_NUMERO_FACTURA_FK IN G2_SC508_VT_PROYECTO.FIDE_DETALLE_FACTURA_TB.FACTURACION_ID_NUMERO_FACTURA_FK%TYPE,
        P_NUMERO_LINEA                     IN G2_SC508_VT_PROYECTO.FIDE_DETALLE_FACTURA_TB.NUMERO_LINEA%TYPE,
        P_CANTIDAD                         IN G2_SC508_VT_PROYECTO.FIDE_DETALLE_FACTURA_TB.cantidad%TYPE,
        P_PRECIO_UNITARIO                  IN G2_SC508_VT_PROYECTO.FIDE_DETALLE_FACTURA_TB.precio_unitario%TYPE,
        P_SUBTOTAL_LINEA                   IN G2_SC508_VT_PROYECTO.FIDE_DETALLE_FACTURA_TB.subtotal_linea%TYPE
    );

    PROCEDURE FIDE_DETALLE_FACTURA_ELIMINAR_SP (
        P_FACTURACION_ID_NUMERO_FACTURA_FK IN G2_SC508_VT_PROYECTO.FIDE_DETALLE_FACTURA_TB.FACTURACION_ID_NUMERO_FACTURA_FK%TYPE,
        P_NUMERO_LINEA                     IN G2_SC508_VT_PROYECTO.FIDE_DETALLE_FACTURA_TB.NUMERO_LINEA%TYPE
    );

    /*
    ============================================================
    ======== CURSORES PARA LECTURAS DE TODAS LAS TABLAS ========
    ============================================================
    
    - Se usa SYS_REFCURSOR para poder enviar los datos a Node.js
    */
    PROCEDURE FIDE_ESTADOS_LISTAR_SP (P_CURSOR OUT SYS_REFCURSOR);
    PROCEDURE FIDE_ROLES_LISTAR_SP (P_CURSOR OUT SYS_REFCURSOR);
    PROCEDURE FIDE_PROVINCIA_LISTAR_SP (P_CURSOR OUT SYS_REFCURSOR);
    PROCEDURE FIDE_METODO_PAGO_LISTAR_SP (P_CURSOR OUT SYS_REFCURSOR);
    PROCEDURE FIDE_CATEGORIA_PRODUCTO_LISTAR_SP (P_CURSOR OUT SYS_REFCURSOR);
    PROCEDURE FIDE_CATEGORIA_SERVICIO_LISTAR_SP (P_CURSOR OUT SYS_REFCURSOR);
    PROCEDURE FIDE_PAQUETE_LISTAR_SP (P_CURSOR OUT SYS_REFCURSOR);
    PROCEDURE FIDE_CANTON_LISTAR_SP (P_CURSOR OUT SYS_REFCURSOR);
    PROCEDURE FIDE_DISTRITO_LISTAR_SP (P_CURSOR OUT SYS_REFCURSOR);
    PROCEDURE FIDE_USUARIOS_LISTAR_SP (P_CURSOR OUT SYS_REFCURSOR);
    PROCEDURE FIDE_PRODUCTOS_LISTAR_SP (P_CURSOR OUT SYS_REFCURSOR);
    PROCEDURE FIDE_SERVICIOS_LISTAR_SP (P_CURSOR OUT SYS_REFCURSOR);
    PROCEDURE FIDE_PAGOS_LISTAR_SP (P_CURSOR OUT SYS_REFCURSOR);
    PROCEDURE FIDE_CLIENTES_LISTAR_SP (P_CURSOR OUT SYS_REFCURSOR);
    PROCEDURE FIDE_EMPLEADOS_LISTAR_SP (P_CURSOR OUT SYS_REFCURSOR);
    PROCEDURE FIDE_CORREO_LISTAR_SP (P_CURSOR OUT SYS_REFCURSOR);
    PROCEDURE FIDE_DIRECCIONES_LISTAR_SP (P_CURSOR OUT SYS_REFCURSOR);
    PROCEDURE FIDE_RESERVACIONES_LISTAR_SP (P_CURSOR OUT SYS_REFCURSOR);
    PROCEDURE FIDE_PAQUETES_POR_SERV_LISTAR_SP (P_CURSOR OUT SYS_REFCURSOR);
    PROCEDURE FIDE_ASIGNACION_LISTAR_SP (P_CURSOR OUT SYS_REFCURSOR);
    PROCEDURE FIDE_DETALLE_RES_LISTAR_SP (P_CURSOR OUT SYS_REFCURSOR);
    PROCEDURE FIDE_FACTURACION_LISTAR_SP (P_CURSOR OUT SYS_REFCURSOR);
    PROCEDURE FIDE_DETALLE_FACT_LISTAR_SP (P_CURSOR OUT SYS_REFCURSOR);

    ---------------------------------------------------------------
    -- FUNCIONES DE APOYO (Lógica de Negocio, Reportes y Consultas)
    ---------------------------------------------------------------

    -----------------------------------------------------------------
    -- 1. FIDE_CLIENTE_NOMBRE_COMPLETO_FN 
    -- Devuelve el nombre completo del usuario (nombre + apellidos).
    -----------------------------------------------------------------
    FUNCTION FIDE_CLIENTE_NOMBRE_COMPLETO_FN(
        P_USUARIOS_ID_CEDULA_PK IN G2_SC508_VT_PROYECTO.FIDE_USUARIOS_TB.USUARIOS_ID_CEDULA_PK%TYPE
    ) RETURN VARCHAR2;

    ---------------------------------------------
    -- 2. FIDE_ESTADO_NOMBRE_FN 
    -- Retorna el nombre del estado según su ID.
    ---------------------------------------------
    FUNCTION FIDE_ESTADO_NOMBRE_FN(
        P_ESTADOS_ID_ESTADO_PK IN G2_SC508_VT_PROYECTO.FIDE_ESTADOS_TB.ESTADOS_ID_ESTADO_PK%TYPE
    ) RETURN VARCHAR2;

    -------------------------------------------------------------------------
    -- 3. FIDE_TOTAL_RESERVACION_FN 
    -- Calcula el total de una reservación (SUM cantidad * precio_unitario).
    -------------------------------------------------------------------------
    FUNCTION FIDE_TOTAL_RESERVACION_FN(
        P_RESERVACIONES_ID_RESERVACION_PK IN G2_SC508_VT_PROYECTO.FIDE_RESERVACIONES_TB.RESERVACIONES_ID_RESERVACION_PK%TYPE
    ) RETURN NUMBER;

    ---------------------------------------------------
    -- 4. FIDE_CALCULAR_IMPUESTO_FN 
    -- Calcula el impuesto del 13% para un monto base.
    ---------------------------------------------------
    FUNCTION FIDE_CALCULAR_IMPUESTO_FN(
        P_MONTO_BASE IN NUMBER
    ) RETURN NUMBER;

    --------------------------------------------------------------------------------
    -- 5. FIDE_CONTAR_RESERVACIONES_CLIENTE_FN 
    -- Retorna cuántas reservaciones tiene un cliente dentro de un rango de fechas.
    --------------------------------------------------------------------------------
    FUNCTION FIDE_CONTAR_RESERVACIONES_CLIENTE_FN(
        P_USUARIOS_ID_CEDULA_PK IN G2_SC508_VT_PROYECTO.FIDE_RESERVACIONES_TB.USUARIOS_ID_CEDULA_PK%TYPE,
        P_FECHA_INICIO          IN DATE,
        P_FECHA_FIN             IN DATE
    ) RETURN NUMBER;

    -------------------------------------------------------------------------------
    -- 6. FIDE_DISPONIBILIDAD_SERVICIO_FN 
    -- Verifica cuántas reservaciones se traslapan con un horario para un servicio.
    -------------------------------------------------------------------------------
    FUNCTION FIDE_DISPONIBILIDAD_SERVICIO_FN(
        P_SERVICIOS_ID_SERVICIO_PK IN G2_SC508_VT_PROYECTO.FIDE_SERVICIOS_TB.SERVICIOS_ID_SERVICIO_PK%TYPE,
        P_FECHA_RESERVACION        IN DATE,
        P_HORA_INICIO              IN TIMESTAMP,
        P_HORA_FIN                 IN TIMESTAMP
    ) RETURN NUMBER;

    ------------------------------------------------------
    -- 7. FIDE_TOTAL_FACTURA_FN 
    -- Retorna el monto total de una factura específica.
    ------------------------------------------------------
    FUNCTION FIDE_TOTAL_FACTURA_FN(
        P_FACTURACION_ID_NUMERO_FACTURA_PK IN G2_SC508_VT_PROYECTO.FIDE_FACTURACION_TB.FACTURACION_ID_NUMERO_FACTURA_PK%TYPE
    ) RETURN NUMBER;
    
    -----------------------------------------------------------
    -- 8. FIDE_CLIENTE_CORREO_PRINCIPAL_FN
    -- Retorna el correo principal activo asociado al usuario.
    -----------------------------------------------------------
    FUNCTION FIDE_CLIENTE_CORREO_PRINCIPAL_FN(
        P_USUARIOS_ID_CEDULA_PK IN VARCHAR2
    ) RETURN VARCHAR2;
    
    ------------------------------------------------------------------------
    -- 9. FIDE_CLIENTE_TELEFONO_FN
    -- Devuelve el número telefónico registrado del cliente.
    ------------------------------------------------------------------------
    FUNCTION FIDE_CLIENTE_TELEFONO_FN(
        P_USUARIOS_ID_CEDULA_PK IN VARCHAR2
    ) RETURN VARCHAR2;
    
    -------------------------------------------------------------------------------
    -- 10. FIDE_DURACION_RESERVA_HORAS_FN
    -- Calcula la duración en horas de una reservación específica.
    -------------------------------------------------------------------------------
    FUNCTION FIDE_DURACION_RESERVA_HORAS_FN(
        P_RESERVACIONES_ID_RESERVACION_PK IN NUMBER
    ) RETURN NUMBER;
    
    -----------------------------------------------------------------------
    -- 11. FIDE_CALCULAR_SUBTOTAL_FN
    -- Calcula el subtotal multiplicando cantidad por precio unitario.
    -----------------------------------------------------------------------
    FUNCTION FIDE_CALCULAR_SUBTOTAL_FN(
        P_CANTIDAD IN NUMBER,
        P_PRECIO_UNITARIO IN NUMBER
    ) RETURN NUMBER;
    
    ---------------------------------------------------------------------------------------
    -- 12. FIDE_TOTAL_DETALLE_FACTURA_FN
    -- Retorna la suma total de los subtotales de detalle para una factura dada.
    ---------------------------------------------------------------------------------------
    FUNCTION FIDE_TOTAL_DETALLE_FACTURA_FN(
        P_FACTURACION_ID_NUMERO_FACTURA_PK IN NUMBER
    ) RETURN NUMBER;
    
    ----------------------------------------------------------------------------------------
    -- 13. FIDE_IMPUESTO_FACTURA_FN
    -- Calcula el impuesto total (13%) basado en los detalles de la factura.
    ----------------------------------------------------------------------------------------
    FUNCTION FIDE_IMPUESTO_FACTURA_FN(
        P_FACTURACION_ID_NUMERO_FACTURA_PK IN NUMBER
    ) RETURN NUMBER;
    
    -------------------------------------------------------------------------------
    -- 14. FIDE_TOTAL_PAQUETE_FN
    -- Suma los precios de los servicios asociados a un paquete.
    -------------------------------------------------------------------------------
    FUNCTION FIDE_TOTAL_PAQUETE_FN(
        P_PAQUETE_ID_PAQUETE_PK IN NUMBER
    ) RETURN NUMBER;
    
    -------------------------------------------------------------------------------
    -- 15. FIDE_ESTADO_OBJETO_FN
    -- Retorna el nombre del estado según su ID (para cualquier tabla con FK estado).
    -------------------------------------------------------------------------------
    FUNCTION FIDE_ESTADO_OBJETO_FN(
        P_ESTADO_ID IN NUMBER
    ) RETURN VARCHAR2;

END FIDE_PROYECTO_FINAL_PKG;